import { defineConfig } from 'orval';
import { loadEnv } from 'vite';

const env = loadEnv('development', process.cwd(), '');
const targetUrl = `${env.API_BASE_URL}/openapi/v1.json`;

export default defineConfig({
  api: {
    input: {
      target: targetUrl,
      override: {
        transformer: (api) => {
          console.log("TRANSFORMER RAN");
          if (api.components?.schemas) {
            const schemas = api.components.schemas;
            const renamed: Record<string, any> = {};
            const renameMap: Record<string, string> = {};

            Object.keys(schemas).forEach(key => {
              let newKey = key.replace(/Command$/, '');
              if (newKey !== key) {
                renameMap[`#/components/schemas/${key}`] = `#/components/schemas/${newKey}`;
              }
              renamed[newKey] = schemas[key];
            });
            api.components.schemas = renamed;

            // Fix invalid $ref pointers (e.g. self-referencing tree DTOs generated by .NET 10 OpenAPI)
            Object.keys(renamed).forEach(schemaName => {
              const targetSchema = renamed[schemaName];
              if (!targetSchema) return;

              const fixRefs = (obj: any) => {
                if (typeof obj !== 'object' || obj === null) return;
                if (obj.$ref) {
                  if (renameMap[obj.$ref]) {
                    obj.$ref = renameMap[obj.$ref];
                  }
                  if (typeof obj.$ref === 'string' && (obj.$ref.includes('/#/') || obj.$ref.includes('properties/data/items'))) {
                    obj.$ref = `#/components/schemas/${schemaName}`;
                  }
                }
                for (const k in obj) {
                  fixRefs(obj[k]);
                }
              };
              fixRefs(targetSchema);
            });

            const replaceRefs = (obj: any) => {
              if (typeof obj !== 'object' || obj === null) return;
              if (obj.$ref && renameMap[obj.$ref]) {
                obj.$ref = renameMap[obj.$ref];
              }
              for (const k in obj) {
                replaceRefs(obj[k]);
              }
            };
            if (api.paths) {
              replaceRefs(api.paths);
            }
          }
          return api;
        }
      }
    },
    output: {
      mode: 'tags',
      target: 'src/api/endpoints',
      schemas: 'src/api/model',
      client: 'react-query',
      httpClient: 'axios',
      mock: false,
      override: {
        mutator: {
          path: 'src/lib/api-client.ts',
          name: 'customInstance',
        },
        operationName: (operation, route, verb) => {
          let name = '';
          if (operation.operationId) {
            name = operation.operationId;
          } else {
            const parts = route.split('/').filter(Boolean);
            const lastPart = parts[parts.length - 1];
            name = lastPart.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
          }
          // Strip leading 'get' / 'Get' from operation names to avoid 'getGet...MutationOptions' / 'getGet...QueryOptions' in Orval
          if (/^get/i.test(name) && name.length > 3) {
            name = name.replace(/^get/i, '');
          }
          // Ensure camelCase (lowercase first letter) for functions
          return name.charAt(0).toLowerCase() + name.slice(1);
        },
      },
    },
  },
});
