<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mapster" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nova.Modules.Identity.Domain\Nova.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\Nova.Contracts\Nova.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Framework\Nova.Framework.Application\Nova.Framework.Application.csproj" />
    <ProjectReference Include="..\..\..\Framework\Nova.Framework.MultiTenancy\Nova.Framework.MultiTenancy.csproj" />
  </ItemGroup>

</Project>
