<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nova.Modules.Multitenancy.Application\Nova.Modules.Multitenancy.Application.csproj" />
    <ProjectReference Include="..\Nova.Modules.Multitenancy.Infrastructure\Nova.Modules.Multitenancy.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Framework\Nova.Framework.Web\Nova.Framework.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit.Abstractions" />
    <PackageReference Include="Mapster" />
  </ItemGroup>

</Project>
