<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" />
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nova.Framework.Domain\Nova.Framework.Domain.csproj" />
    <ProjectReference Include="..\Nova.Framework.Persistence\Nova.Framework.Persistence.csproj" />
  </ItemGroup>

</Project>
