/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfLogin,
  ApiResponseOfRegisterUser,
  ApiResponseOfSendEmailLoginCode,
  ApiResponseOfSendEmailRegisterCode,
  EmailLogin,
  Login,
  RefreshToken,
  RegisterUser,
  SendEmailLoginCode,
  SendEmailRegisterCode
} from '../../model';

import { customInstance } from '../../../lib/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 通过邮箱和收到的验证码直接登录获取 Token
 * @summary 邮箱验证码登录
 */
export const emailLogin = (
    emailLogin: EmailLogin,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLogin>(
      {url: `/api/identity/email-login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailLogin, signal
    },
      options);
    }




export const getEmailLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext> => {

const mutationKey = ['emailLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof emailLogin>>, {data: EmailLogin}> = (props) => {
          const {data} = props ?? {};

          return  emailLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EmailLoginMutationResult = NonNullable<Awaited<ReturnType<typeof emailLogin>>>
    export type EmailLoginMutationBody = EmailLogin
    export type EmailLoginMutationError = unknown

    /**
 * @summary 邮箱验证码登录
 */
export const useEmailLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof emailLogin>>,
        TError,
        {data: EmailLogin},
        TContext
      > => {
      return useMutation(getEmailLoginMutationOptions(options), queryClient);
    }
    /**
 * 通过用户名和密码获取身份认证 Token
 * @summary 用户登录
 */
export const login = (
    loginNull: Login | null,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLogin>(
      {url: `/api/identity/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginNull, signal
    },
      options);
    }




export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login | null}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login | null}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: Login | null}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = Login | null
    export type LoginMutationError = unknown

    /**
 * @summary 用户登录
 */
export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login | null}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: Login | null},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    /**
 * 使用 RefreshToken 获取新的 AccessToken
 * @summary 刷新令牌
 */
export const refresh = (
    refreshToken: RefreshToken,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLogin>(
      {url: `/api/identity/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshToken, signal
    },
      options);
    }




export const getRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{data: RefreshToken}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{data: RefreshToken}, TContext> => {

const mutationKey = ['refresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refresh>>, {data: RefreshToken}> = (props) => {
          const {data} = props ?? {};

          return  refresh(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshMutationResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
    export type RefreshMutationBody = RefreshToken
    export type RefreshMutationError = unknown

    /**
 * @summary 刷新令牌
 */
export const useRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{data: RefreshToken}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refresh>>,
        TError,
        {data: RefreshToken},
        TContext
      > => {
      return useMutation(getRefreshMutationOptions(options), queryClient);
    }
    /**
 * 注册一个新的用户账户
 * @summary 用户注册
 */
export const register = (
    registerUserNull: RegisterUser | null,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfRegisterUser>(
      {url: `/api/identity/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerUserNull, signal
    },
      options);
    }




export const getRegisterMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUser | null}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUser | null}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: RegisterUser | null}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = RegisterUser | null
    export type RegisterMutationError = unknown

    /**
 * @summary 用户注册
 */
export const useRegister = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: RegisterUser | null}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: RegisterUser | null},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options), queryClient);
    }
    /**
 * 通过邮箱发送用于免密登录的 6 位数验证码
 * @summary 发送登录验证码
 */
export const sendLoginCode = (
    sendEmailLoginCodeNull: SendEmailLoginCode | null,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendEmailLoginCode>(
      {url: `/api/identity/send-login-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendEmailLoginCodeNull, signal
    },
      options);
    }




export const getSendLoginCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendLoginCode>>, TError,{data: SendEmailLoginCode | null}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendLoginCode>>, TError,{data: SendEmailLoginCode | null}, TContext> => {

const mutationKey = ['sendLoginCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendLoginCode>>, {data: SendEmailLoginCode | null}> = (props) => {
          const {data} = props ?? {};

          return  sendLoginCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendLoginCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendLoginCode>>>
    export type SendLoginCodeMutationBody = SendEmailLoginCode | null
    export type SendLoginCodeMutationError = unknown

    /**
 * @summary 发送登录验证码
 */
export const useSendLoginCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendLoginCode>>, TError,{data: SendEmailLoginCode | null}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendLoginCode>>,
        TError,
        {data: SendEmailLoginCode | null},
        TContext
      > => {
      return useMutation(getSendLoginCodeMutationOptions(options), queryClient);
    }
    /**
 * 通过邮箱发送用于注册的 6 位数验证码
 * @summary 发送注册验证码
 */
export const sendRegisterCode = (
    sendEmailRegisterCodeNull: SendEmailRegisterCode | null,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendEmailRegisterCode>(
      {url: `/api/identity/send-register-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendEmailRegisterCodeNull, signal
    },
      options);
    }




export const getSendRegisterCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendRegisterCode>>, TError,{data: SendEmailRegisterCode | null}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendRegisterCode>>, TError,{data: SendEmailRegisterCode | null}, TContext> => {

const mutationKey = ['sendRegisterCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendRegisterCode>>, {data: SendEmailRegisterCode | null}> = (props) => {
          const {data} = props ?? {};

          return  sendRegisterCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendRegisterCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendRegisterCode>>>
    export type SendRegisterCodeMutationBody = SendEmailRegisterCode | null
    export type SendRegisterCodeMutationError = unknown

    /**
 * @summary 发送注册验证码
 */
export const useSendRegisterCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendRegisterCode>>, TError,{data: SendEmailRegisterCode | null}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendRegisterCode>>,
        TError,
        {data: SendEmailRegisterCode | null},
        TContext
      > => {
      return useMutation(getSendRegisterCodeMutationOptions(options), queryClient);
    }
