<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Finbuckle.MultiTenant.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.OpenApi.Readers" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nova.Modules.Mcp.Domain\Nova.Modules.Mcp.Domain.csproj" />
    <ProjectReference Include="..\Nova.Modules.Mcp.Application\Nova.Modules.Mcp.Application.csproj" />
    <ProjectReference Include="..\..\..\Framework\Nova.Framework.MultiTenancy\Nova.Framework.MultiTenancy.csproj" />
    <ProjectReference Include="..\..\..\Framework\Nova.Framework.Persistence\Nova.Framework.Persistence.csproj" />
  </ItemGroup>

</Project>
