/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type AdminResetUserPasswordResult = {
  /** 是否成功 */
  success?: boolean;
  /**
     * 错误信息
     * @nullable
     */
  message?: string | null;
} | null;
