/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UpdatePreferencesResult } from './updatePreferencesResult';

export interface ApiResponseOfUpdatePreferencesResult {
  code?: number;
  message?: string;
  data?: UpdatePreferencesResult | null;
}
