/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SendEmailRegisterCode } from './sendEmailRegisterCode';

export interface ApiResponseOfSendEmailRegisterCode {
  code?: number;
  message?: string;
  data?: SendEmailRegisterCode | null;
}
