/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RestoreTrashBinItemResult } from './restoreTrashBinItemResult';

export interface ApiResponseOfRestoreTrashBinItemResult {
  code?: number;
  message?: string;
  data?: RestoreTrashBinItemResult | null;
}
