/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationTreeDto } from './organizationTreeDto';

export interface ApiResponseOfListOfOrganizationTreeDto {
  code?: number;
  message?: string;
  /** @nullable */
  data?: OrganizationTreeDto[] | null;
}
