/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { LoginResult } from './loginResult';

export interface ApiResponseOfLoginResult {
  code?: number;
  message?: string;
  data?: LoginResult | null;
}
