/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DictionaryItemDto } from './dictionaryItemDto';

export interface ApiResponseOfListOfDictionaryItemDto {
  code?: number;
  message?: string;
  /** @nullable */
  data?: DictionaryItemDto[] | null;
}
