/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResultOfOrganizationDto } from './pagedResultOfOrganizationDto';

export interface ApiResponseOfPagedResultOfOrganizationDto {
  code?: number;
  message?: string;
  data?: PagedResultOfOrganizationDto | null;
}
