/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserPreferenceDto } from './userPreferenceDto';

export interface ApiResponseOfUserPreferenceDto {
  code?: number;
  message?: string;
  data?: UserPreferenceDto | null;
}
