/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SendForgotPasswordCodeResult } from './sendForgotPasswordCodeResult';

export interface ApiResponseOfSendForgotPasswordCodeResult {
  code?: number;
  message?: string;
  data?: SendForgotPasswordCodeResult | null;
}
