/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { MarkNotificationAsReadResult } from './markNotificationAsReadResult';

export interface ApiResponseOfMarkNotificationAsReadResult {
  code?: number;
  message?: string;
  data?: MarkNotificationAsReadResult | null;
}
