/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { RolePermissionsDto } from './rolePermissionsDto';

export interface ApiResponseOfRolePermissionsDto {
  code?: number;
  message?: string;
  data?: RolePermissionsDto | null;
}
