/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationDto } from './organizationDto';

export interface ApiResponseOfOrganizationDto2 {
  code?: number;
  message?: string;
  data?: OrganizationDto | null;
}
