/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResultOfDictionaryItemDto } from './pagedResultOfDictionaryItemDto';

export interface ApiResponseOfPagedResultOfDictionaryItemDto {
  code?: number;
  message?: string;
  data?: PagedResultOfDictionaryItemDto | null;
}
