/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { PagedResultOfRoleDto } from './pagedResultOfRoleDto';

export interface ApiResponseOfPagedResultOfRoleDto {
  code?: number;
  message?: string;
  data?: PagedResultOfRoleDto | null;
}
