/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentDto } from './attachmentDto';

/**
 * @nullable
 */
export type ApiResponseOfListOfAttachmentDto = {
  code?: number;
  message?: string;
  /** @nullable */
  data?: AttachmentDto[] | null;
} | null;
