/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ApiResponseOfGuid = {
  code?: number;
  message?: string;
  data?: string;
} | null;
