/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentType } from './attachmentType';

export interface AttachmentDto {
  id?: string;
  fileId?: string;
  targetType?: string;
  targetId?: string;
  attachmentType?: AttachmentType;
  sort?: number;
  /** @nullable */
  remarks?: string | null;
  fileName?: string;
  fileKey?: string;
  fileSize?: number;
  contentType?: string;
  accessUrl?: string;
  createdAt?: string;
}
