/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface AuthAuditLogDto {
  id?: string;
  eventType?: string;
  /** @nullable */
  account?: string | null;
  /** @nullable */
  userId?: string | null;
  success?: boolean;
  /** @nullable */
  reason?: string | null;
  /** @nullable */
  ipAddress?: string | null;
  occurredOn?: string;
  createdAt?: string;
}
