/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { AttachmentType } from './attachmentType';

export interface BindAttachment {
  fileId?: string;
  targetType?: string;
  targetId?: string;
  attachmentType?: AttachmentType;
  sort?: number;
  /** @nullable */
  remarks?: string | null;
}
