/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ChangePassword {
  /** 旧密码 */
  oldPassword?: string;
  /** 新密码 */
  newPassword?: string;
}
