/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type ChangePasswordResult = {
  /** 是否修改成功 */
  success?: boolean;
} | null;
