/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type CreateRoleResult = {
  /** 新创建角色的唯一标识 ID */
  roleId?: string;
} | null;
