/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateRole {
  /** 角色名称 */
  name?: string;
  /** 显示名称 */
  displayName?: string;
  /**
     * 备注
     * @nullable
     */
  remarks?: string | null;
  /** 排序 */
  sort?: number;
  /** 是否启用 */
  isEnabled?: boolean;
  /**
     * 权限列表
     * @nullable
     */
  permissions?: string[] | null;
}
