/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateMenu {
  /**
     * 父级ID
     * @nullable
     */
  parentId?: string | null;
  /** 菜单名称 */
  name?: string;
  /** 路由地址 */
  path?: string;
  /** 组件路径 */
  component?: string;
  /**
     * 图标名称
     * @nullable
     */
  icon?: string | null;
  /**
     * 备注
     * @nullable
     */
  remarks?: string | null;
  /** 排序 */
  sort?: number;
  /** 是否启用 */
  isEnabled?: boolean;
}
