/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface CreateOrganization {
  name?: string;
  /** @nullable */
  parentId?: string | null;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  type?: string | null;
  sort?: number;
  /** @nullable */
  leaderUserId?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  remarks?: string | null;
}
