/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface DictionaryTypeDto {
  id?: string;
  code?: string;
  name?: string;
  /** @nullable */
  description?: string | null;
  isSystem?: boolean;
  isEnabled?: boolean;
  sortOrder?: number;
  createdAt?: string;
}
