/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface EmailLogin {
  /** 邮箱 */
  email?: string;
  /** 验证码 */
  code?: string;
  /**
     * 目标租户
     * @nullable
     */
  targetTenantId?: string | null;
}
