/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface EntityPropertyChangeDto {
  /** 明细标识 */
  id?: string;
  /** 属性字段名称 */
  propertyName?: string;
  /**
     * 属性显示名称
     * @nullable
     */
  propertyDisplayName?: string | null;
  /**
     * 修改前原始值
     * @nullable
     */
  originalValue?: string | null;
  /**
     * 修改后最新值
     * @nullable
     */
  newValue?: string | null;
}
