/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EntityPropertyChangeDto } from './entityPropertyChangeDto';

export interface EntityChangeLogDto {
  /** 日志标识 */
  id?: string;
  /** 实体类型 */
  entityType?: string;
  /** 实体主键 */
  entityId?: string;
  /** 变更类型 */
  changeType?: string;
  /**
     * 操作人标识
     * @nullable
     */
  operatorId?: string | null;
  /**
     * 操作人账号
     * @nullable
     */
  operatorName?: string | null;
  /** 变更发生时间 */
  createdAt?: string;
  /** 变动字段明细 */
  propertyChanges?: EntityPropertyChangeDto[];
}
