/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface EntityFieldMetadataDto {
  name?: string;
  displayName?: string;
  type?: string;
  supportMasking?: boolean;
}
