/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { StorageAccessMode } from './storageAccessMode';
import type { StorageProviderType } from './storageProviderType';

/**
 * @nullable
 */
export type FileObject = {
  fileName?: string;
  fileKey?: string;
  bucketName?: string;
  contentType?: string;
  fileSize?: number;
  /** @nullable */
  fileHash?: string | null;
  provider?: StorageProviderType;
  accessMode?: StorageAccessMode;
  /** @nullable */
  accessUrl?: string | null;
  /** @nullable */
  createdBy?: string | null;
  createdAt?: string;
  /** @nullable */
  modifiedBy?: string | null;
  /** @nullable */
  modifiedAt?: string | null;
  /** @nullable */
  deletedBy?: string | null;
  /** @nullable */
  deletedAt?: string | null;
  isDeleted?: boolean;
  /** @nullable */
  remarks?: string | null;
  sort?: number;
  isEnabled?: boolean;
  id?: string;
} | null;
