/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type FilesParams = {
page?: number;
pageSize?: number;
search?: string;
category?: string;
};
