/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetEntityChangesParams = {
page: number;
pageSize: number;
entityType?: string;
entityId?: string;
changeType?: string;
operatorName?: string;
startDate?: string;
endDate?: string;
};
