/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ImportOpenApi {
  serverName?: string;
  baseUrl?: string;
  swaggerJson?: string;
  /** @nullable */
  swaggerUrl?: string | null;
  /** @nullable */
  authToken?: string | null;
}
