/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type InstantUploadResult = {
  isInstant?: boolean;
  /** @nullable */
  fileId?: string | null;
  /** @nullable */
  fileKey?: string | null;
  /** @nullable */
  accessUrl?: string | null;
} | null;
