/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface InstantUpload {
  fileHash?: string;
  fileSize?: number;
  fileName?: string;
  contentType?: string;
}
