/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface Login {
  /** 账号 */
  account?: string;
  /** 密码 */
  password?: string;
  /**
     * 目标租户
     * @nullable
     */
  targetTenantId?: string | null;
}
