/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type LoginResult = {
  /** JWT Token，需在请求头带上 Bearer {Token} */
  token?: string;
  /** 刷新令牌，用于在 AccessToken 过期后获取新的 Token */
  refreshToken?: string;
  /** 访问令牌的过期时间（单位：秒） */
  expiresIn?: number;
} | null;
