/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TenantOptionDto } from './tenantOptionDto';

/**
 * @nullable
 */
export type LoginResult = {
  /** 访问令牌 */
  token?: string;
  /** 刷新令牌 */
  refreshToken?: string;
  /** 过期秒数 */
  expiresIn?: number;
  /** 需选择租户 */
  requiresTenantSelection?: boolean;
  /**
     * 可用租户列表
     * @nullable
     */
  availableTenants?: TenantOptionDto[] | null;
} | null;
