/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface Logout {
  /** 当前的 AccessToken（即使已过期也需提供，用于提取用户与租户信息） */
  accessToken?: string;
  /** 要吊销的刷新令牌 */
  refreshToken?: string;
}
