/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface McpKeyDto {
  id?: string;
  name?: string;
  keyValue?: string;
  createdAt?: string;
}
