/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface MenuDto {
  id?: string;
  /** @nullable */
  parentId?: string | null;
  name?: string;
  path?: string;
  component?: string;
  /** @nullable */
  icon?: string | null;
  sort?: number;
  /** @nullable */
  remarks?: string | null;
  isEnabled?: boolean;
  createdAt?: string;
}
