/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SanitizationDetailDto } from './sanitizationDetailDto';

export interface OperationLogDto {
  /** ID */
  id?: string;
  /**
     * TraceId
     * @nullable
     */
  traceId?: string | null;
  /**
     * 用户ID
     * @nullable
     */
  userId?: string | null;
  /**
     * 客户端IP
     * @nullable
     */
  clientIp?: string | null;
  /**
     * 请求方法
     * @nullable
     */
  httpMethod?: string | null;
  /**
     * 请求路径
     * @nullable
     */
  requestPath?: string | null;
  /**
     * 操作名称
     * @nullable
     */
  actionName?: string | null;
  /**
     * 请求体
     * @nullable
     */
  requestPayload?: string | null;
  /**
     * 响应体
     * @nullable
     */
  responsePayload?: string | null;
  /**
     * 状态码
     * @nullable
     */
  statusCode?: number | null;
  /**
     * 耗时(ms)
     * @nullable
     */
  elapsedMs?: number | null;
  /**
     * 执行状态
     * @nullable
     */
  status?: string | null;
  /**
     * 是否慢请求
     * @nullable
     */
  isSlowRequest?: boolean | null;
  /**
     * 含脱敏数据
     * @nullable
     */
  hasSanitizedData?: boolean | null;
  /**
     * 错误信息
     * @nullable
     */
  errorMessage?: string | null;
  /**
     * 异常堆栈
     * @nullable
     */
  exceptionStackTrace?: string | null;
  /**
     * 记录时间
     * @nullable
     */
  createdAt?: string | null;
  /** 脱敏明细 */
  sanitizationDetails?: SanitizationDetailDto[];
}
