/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { SanitizationDetailDto } from './sanitizationDetailDto';

export interface OperationLogDto {
  /** 日志主键 ID */
  id?: string;
  /**
     * 链路追踪 Trace ID
     * @nullable
     */
  traceId?: string | null;
  /**
     * 操作用户 ID
     * @nullable
     */
  userId?: string | null;
  /**
     * 客户端 IP 地址
     * @nullable
     */
  clientIp?: string | null;
  /**
     * HTTP 请求谓词
     * @nullable
     */
  httpMethod?: string | null;
  /**
     * HTTP 请求路径
     * @nullable
     */
  requestPath?: string | null;
  /**
     * 操作/动作名称
     * @nullable
     */
  actionName?: string | null;
  /**
     * 脱敏后的请求载荷 JSON
     * @nullable
     */
  requestPayload?: string | null;
  /**
     * 响应载荷 JSON
     * @nullable
     */
  responsePayload?: string | null;
  /**
     * HTTP 状态码
     * @nullable
     */
  statusCode?: number | null;
  /**
     * 执行耗时 (毫秒)
     * @nullable
     */
  elapsedMs?: number | null;
  /**
     * 执行状态 (InProgress / Success / Failed)
     * @nullable
     */
  status?: string | null;
  /**
     * 是否为慢请求
     * @nullable
     */
  isSlowRequest?: boolean | null;
  /**
     * 是否包含脱敏数据
     * @nullable
     */
  hasSanitizedData?: boolean | null;
  /**
     * 错误信息 (仅失败时存在)
     * @nullable
     */
  errorMessage?: string | null;
  /**
     * 异常堆栈轨迹
     * @nullable
     */
  exceptionStackTrace?: string | null;
  /**
     * 日志记录时间
     * @nullable
     */
  createdAt?: string | null;
  /** 敏感数据脱敏明细列表 */
  sanitizationDetails?: SanitizationDetailDto[];
}
