/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OrganizationDto2 {
  id?: string;
  /** @nullable */
  parentId?: string | null;
  name?: string;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  type?: string | null;
  level?: number;
  sort?: number;
  /** @nullable */
  leaderUserId?: string | null;
  /** @nullable */
  leaderUserName?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  isEnabled?: boolean;
  /** @nullable */
  remarks?: string | null;
  createdAt?: string;
  memberCount?: number;
}
