/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface OrganizationTreeDto {
  id?: string;
  /** @nullable */
  parentId?: string | null;
  name?: string;
  /** @nullable */
  code?: string | null;
  /** @nullable */
  type?: string | null;
  level?: number;
  sort?: number;
  isEnabled?: boolean;
  memberCount?: number;
  children?: OrganizationTreeDto[];
}
