/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationDto2 } from './organizationDto2';

/**
 * @nullable
 */
export type PagedResultOfOrganizationDto = {
  total?: number;
  items?: OrganizationDto2[];
  /** @nullable */
  page?: number | null;
  /** @nullable */
  pageSize?: number | null;
  /** @nullable */
  totalPages?: number | null;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
  isFirstPage?: boolean;
  isLastPage?: boolean;
} | null;
