/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { UserDto } from './userDto';

/**
 * @nullable
 */
export type PagedResultOfUserDto = {
  total?: number;
  items?: UserDto[];
  /** @nullable */
  page?: number | null;
  /** @nullable */
  pageSize?: number | null;
  /** @nullable */
  totalPages?: number | null;
  hasPreviousPage?: boolean;
  hasNextPage?: boolean;
  isFirstPage?: boolean;
  isLastPage?: boolean;
} | null;
