/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ParseSwagger {
  /** @nullable */
  swaggerUrl?: string | null;
  /** @nullable */
  swaggerJson?: string | null;
  /** @nullable */
  authToken?: string | null;
}
