/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { ProfileRoleDto } from './profileRoleDto';

/**
 * @nullable
 */
export type ProfileDto = {
  /** 用户ID */
  id?: string;
  /** 用户名 */
  userName?: string;
  /**
     * 邮箱
     * @nullable
     */
  email?: string | null;
  /** 邮箱已验证 */
  emailConfirmed?: boolean;
  /**
     * 手机号
     * @nullable
     */
  phoneNumber?: string | null;
  /**
     * 昵称
     * @nullable
     */
  nickName?: string | null;
  /**
     * 头像地址
     * @nullable
     */
  avatarUrl?: string | null;
  /**
     * 简介
     * @nullable
     */
  bio?: string | null;
  /** 所属角色 */
  roles?: ProfileRoleDto[];
  /**
     * 所属租户
     * @nullable
     */
  tenantId?: string | null;
  /** 注册时间 */
  createdAt?: string;
} | null;
