/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface ProfileRoleDto {
  /** 角色名 */
  name?: string;
  /** 显示名称 */
  displayName?: string;
}
