/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RefreshToken {
  /** 当前的 AccessToken（即使已过期也需要提供，用于提取用户信息） */
  accessToken?: string;
  /** 刷新令牌 */
  refreshToken?: string;
}
