/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RegisterUser {
  /** 用户名 */
  username?: string;
  /** 邮箱 */
  email?: string;
  /** 密码 */
  password?: string;
  /** 确认密码 */
  confirmPassword?: string;
  /** 邮箱验证码 */
  emailCode?: string;
}
