/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RestoreTrashBinItem {
  /** 实体类型 */
  entityType?: string;
  /** 数据标识 */
  id?: string;
}
