/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface RoleDto {
  id?: string;
  /** 角色名称 (代码) */
  name?: string;
  /** 显示名称 */
  displayName?: string;
  /**
     * 备注说明
     * @nullable
     */
  remarks?: string | null;
  /** 排序 */
  sort?: number;
  /** 状态 */
  isEnabled?: boolean;
  /** 创建时间 */
  createdAt?: string;
}
