/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SanitizationDetailDto {
  /** 明细主键 ID */
  id?: string;
  /**
     * 关联日志主键 ID
     * @nullable
     */
  logId?: string | null;
  /**
     * 被遮蔽/脱敏的敏感字段名称
     * @nullable
     */
  fieldName?: string | null;
  /**
     * 脱敏规则标识
     * @nullable
     */
  maskedRule?: string | null;
  /**
     * 脱敏时间
     * @nullable
     */
  sanitizedAt?: string | null;
}
