/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SanitizationDetailDto {
  /** ID */
  id?: string;
  /**
     * 日志ID
     * @nullable
     */
  logId?: string | null;
  /**
     * 字段名
     * @nullable
     */
  fieldName?: string | null;
  /**
     * 脱敏规则
     * @nullable
     */
  maskedRule?: string | null;
  /**
     * 脱敏时间
     * @nullable
     */
  sanitizedAt?: string | null;
}
