/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface StorageFileDto2 {
  id?: string;
  fileName?: string;
  fileKey?: string;
  fileSize?: number;
  contentType?: string;
  accessUrl?: string;
}
