/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface SystemNotificationDto {
  id?: string;
  title?: string;
  content?: string;
  notificationType?: string;
  eventCode?: string;
  /** @nullable */
  referenceId?: string | null;
  /** @nullable */
  payloadJson?: string | null;
  isRead?: boolean;
  createdAt?: string;
  /** @nullable */
  readAt?: string | null;
}
