/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TrashBinItemDto {
  /** 数据标识 */
  id?: string;
  /** 实体类型 */
  entityType?: string;
  /** 显示名称 */
  displayName?: string;
  /**
     * 删除用户ID
     * @nullable
     */
  deletedBy?: string | null;
  /**
     * 删除操作人账号
     * @nullable
     */
  deletedByUserName?: string | null;
  /**
     * 删除时间
     * @nullable
     */
  deletedAt?: string | null;
}
