/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePreferences {
  /**
     * 主题：light / dark / system
     * @nullable
     */
  theme?: string | null;
  /**
     * 界面字体
     * @nullable
     */
  font?: string | null;
  /**
     * 界面语言
     * @nullable
     */
  language?: string | null;
  /**
     * 时区（IANA 名称）
     * @nullable
     */
  timeZone?: string | null;
  /**
     * 推送范围：all / mentions / none
     * @nullable
     */
  notifyType?: string | null;
  /**
     * 接收账户活动邮件
     * @nullable
     */
  communicationEmails?: boolean | null;
  /**
     * 接收产品营销邮件
     * @nullable
     */
  marketingEmails?: boolean | null;
  /**
     * 接收社交动态邮件
     * @nullable
     */
  socialEmails?: boolean | null;
  /**
     * 移动端使用独立通知设置
     * @nullable
     */
  mobileNotifications?: boolean | null;
  /**
     * 在侧边栏中被隐藏的菜单项（菜单 url 集合）
     * @nullable
     */
  hiddenSidebarItems?: string[] | null;
}
