/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateTenant {
  id: string;
  name: string;
  /** @nullable */
  connectionString: string | null;
  adminEmail: string;
  /** @nullable */
  issuer: string | null;
  isActive: boolean;
  validUpto: string;
}
