/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateDictionaryType {
  id?: string;
  name?: string;
  /** @nullable */
  description?: string | null;
  isEnabled?: boolean;
  sortOrder?: number;
}
