/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateDictionaryItem {
  id?: string;
  label?: string;
  value?: string;
  /** @nullable */
  tagType?: string | null;
  sortOrder?: number;
  isDefault?: boolean;
  isEnabled?: boolean;
  /** @nullable */
  remarks?: string | null;
}
