/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUser {
  id?: string;
  /** 用户名 */
  userName?: string;
  /** 用户邮箱 */
  email?: string;
  /**
     * 密码（留空则不修改）
     * @nullable
     */
  password?: string | null;
  /**
     * 手机号
     * @nullable
     */
  phoneNumber?: string | null;
  /** 是否启用 */
  isEnabled?: boolean;
  /**
     * 角色名称列表
     * @nullable
     */
  roles?: string[] | null;
  /**
     * 直接分配的权限标识列表
     * @nullable
     */
  permissions?: string[] | null;
}
