/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdatePreferences {
  /**
     * 主题
     * @nullable
     */
  theme?: string | null;
  /**
     * 字体
     * @nullable
     */
  font?: string | null;
  /**
     * 语言
     * @nullable
     */
  language?: string | null;
  /**
     * 时区
     * @nullable
     */
  timeZone?: string | null;
  /**
     * 通知范围
     * @nullable
     */
  notifyType?: string | null;
  /**
     * 账户邮件
     * @nullable
     */
  communicationEmails?: boolean | null;
  /**
     * 营销邮件
     * @nullable
     */
  marketingEmails?: boolean | null;
  /**
     * 社交邮件
     * @nullable
     */
  socialEmails?: boolean | null;
  /**
     * 移动通知
     * @nullable
     */
  mobileNotifications?: boolean | null;
  /**
     * 隐藏菜单
     * @nullable
     */
  hiddenSidebarItems?: string[] | null;
}
