/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationMemberDto } from './organizationMemberDto';

export interface UpdateOrganizationMembers {
  id?: string;
  members?: OrganizationMemberDto[];
}
