/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateProfile {
  /**
     * 昵称
     * @nullable
     */
  nickName?: string | null;
  /**
     * 简介
     * @nullable
     */
  bio?: string | null;
  /**
     * 头像地址
     * @nullable
     */
  avatarUrl?: string | null;
  /**
     * 手机号
     * @nullable
     */
  phoneNumber?: string | null;
}
