/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUser {
  id?: string;
  /** 用户名 */
  userName?: string;
  /** 邮箱 */
  email?: string;
  /**
     * 密码
     * @nullable
     */
  password?: string | null;
  /**
     * 手机号
     * @nullable
     */
  phoneNumber?: string | null;
  /** 是否启用 */
  isEnabled?: boolean;
  /**
     * 角色列表
     * @nullable
     */
  roles?: string[] | null;
  /**
     * 权限列表
     * @nullable
     */
  permissions?: string[] | null;
  /**
     * 菜单列表
     * @nullable
     */
  menus?: string[] | null;
}
