/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UserPreferenceDto = {
  /** 主题：light / dark / system */
  theme?: string;
  /** 界面字体 */
  font?: string;
  /** 界面语言 */
  language?: string;
  /**
     * 时区（IANA 名称）
     * @nullable
     */
  timeZone?: string | null;
  /** 推送范围：all / mentions / none */
  notifyType?: string;
  /** 接收账户活动邮件 */
  communicationEmails?: boolean;
  /** 接收产品营销邮件 */
  marketingEmails?: boolean;
  /** 接收社交动态邮件 */
  socialEmails?: boolean;
  /** 接收安全提醒邮件（强制开启） */
  securityEmails?: boolean;
  /** 移动端使用独立通知设置 */
  mobileNotifications?: boolean;
  /** 在侧边栏中被隐藏的菜单项（菜单 url 集合） */
  hiddenSidebarItems?: string[];
} | null;
