/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

export interface UserDto {
  id?: string;
  userName?: string;
  email?: string;
  /** @nullable */
  phoneNumber?: string | null;
  isEnabled?: boolean;
  createdAt?: string;
}
