/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type UserPreferenceDto = {
  /** 主题 */
  theme?: string;
  /** 字体 */
  font?: string;
  /** 语言 */
  language?: string;
  /**
     * 时区
     * @nullable
     */
  timeZone?: string | null;
  /** 通知范围 */
  notifyType?: string;
  /** 账户邮件 */
  communicationEmails?: boolean;
  /** 营销邮件 */
  marketingEmails?: boolean;
  /** 社交邮件 */
  socialEmails?: boolean;
  /** 安全邮件 */
  securityEmails?: boolean;
  /** 移动通知 */
  mobileNotifications?: boolean;
  /** 隐藏菜单 */
  hiddenSidebarItems?: string[];
} | null;
