/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfPagedResultOfAuthAuditLogDto,
  ApiResponseOfPagedResultOfOperationLogDto,
  GetOperationLogsParams
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 操作日志列表
 */
export const getOperationLogs = (
    params: GetOperationLogsParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfOperationLogDto>(
      {url: `/api/v1/audit/operation-logs`, method: 'GET',
        params, signal
    },
      options);
    }




export const getGetOperationLogsQueryKey = (params?: GetOperationLogsParams,) => {
    return [
    `/api/v1/audit/operation-logs`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetOperationLogsQueryOptions = <TData = Awaited<ReturnType<typeof getOperationLogs>>, TError = unknown>(params: GetOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOperationLogsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOperationLogs>>> = ({ signal }) => getOperationLogs(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOperationLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOperationLogsQueryResult = NonNullable<Awaited<ReturnType<typeof getOperationLogs>>>
export type GetOperationLogsQueryError = unknown


export function useGetOperationLogs<TData = Awaited<ReturnType<typeof getOperationLogs>>, TError = unknown>(
 params: GetOperationLogsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOperationLogs>>,
          TError,
          Awaited<ReturnType<typeof getOperationLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOperationLogs<TData = Awaited<ReturnType<typeof getOperationLogs>>, TError = unknown>(
 params: GetOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOperationLogs>>,
          TError,
          Awaited<ReturnType<typeof getOperationLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOperationLogs<TData = Awaited<ReturnType<typeof getOperationLogs>>, TError = unknown>(
 params: GetOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 操作日志列表
 */

export function useGetOperationLogs<TData = Awaited<ReturnType<typeof getOperationLogs>>, TError = unknown>(
 params: GetOperationLogsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOperationLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOperationLogsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 审计日志
 */
export const authAuditLogs = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfAuthAuditLogDto>(
      {url: `/api/identity/auth-audit-logs`, method: 'GET', signal
    },
      options);
    }




export const getAuthAuditLogsQueryKey = () => {
    return [
    `/api/identity/auth-audit-logs`
    ] as const;
    }


export const getAuthAuditLogsQueryOptions = <TData = Awaited<ReturnType<typeof authAuditLogs>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthAuditLogsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof authAuditLogs>>> = ({ signal }) => authAuditLogs(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authAuditLogs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthAuditLogsQueryResult = NonNullable<Awaited<ReturnType<typeof authAuditLogs>>>
export type AuthAuditLogsQueryError = unknown


export function useAuthAuditLogs<TData = Awaited<ReturnType<typeof authAuditLogs>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAuditLogs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof authAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthAuditLogs<TData = Awaited<ReturnType<typeof authAuditLogs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAuditLogs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authAuditLogs>>,
          TError,
          Awaited<ReturnType<typeof authAuditLogs>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthAuditLogs<TData = Awaited<ReturnType<typeof authAuditLogs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 审计日志
 */

export function useAuthAuditLogs<TData = Awaited<ReturnType<typeof authAuditLogs>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authAuditLogs>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthAuditLogsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






