/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfChangePasswordResult,
  ApiResponseOfLoginResult,
  ApiResponseOfLogoutResult,
  ApiResponseOfRegisterUserResult,
  ApiResponseOfResetPasswordResult,
  ApiResponseOfSendEmailLoginCodeResult,
  ApiResponseOfSendEmailRegisterCodeResult,
  ApiResponseOfSendForgotPasswordCodeResult,
  ChangePassword,
  EmailLogin,
  Login,
  Logout,
  RefreshToken,
  RegisterUser,
  ResetPassword,
  ResolveTenantParams,
  SendEmailLoginCode,
  SendEmailRegisterCode,
  SendForgotPasswordCode
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 修改密码
 */
export const changePassword = (
    changePassword: ChangePassword,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfChangePasswordResult>(
      {url: `/api/identity/change-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: changePassword, signal
    },
      options);
    }




export const getChangePasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePassword}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePassword}, TContext> => {

const mutationKey = ['changePassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof changePassword>>, {data: ChangePassword}> = (props) => {
          const {data} = props ?? {};

          return  changePassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof changePassword>>>
    export type ChangePasswordMutationBody = ChangePassword
    export type ChangePasswordMutationError = unknown

    /**
 * @summary 修改密码
 */
export const useChangePassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof changePassword>>, TError,{data: ChangePassword}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof changePassword>>,
        TError,
        {data: ChangePassword},
        TContext
      > => {
      return useMutation(getChangePasswordMutationOptions(options), queryClient);
    }
    /**
 * @summary 验证码登录
 */
export const emailLogin = (
    emailLogin: EmailLogin,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLoginResult>(
      {url: `/api/identity/email-login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailLogin, signal
    },
      options);
    }




export const getEmailLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext> => {

const mutationKey = ['emailLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof emailLogin>>, {data: EmailLogin}> = (props) => {
          const {data} = props ?? {};

          return  emailLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EmailLoginMutationResult = NonNullable<Awaited<ReturnType<typeof emailLogin>>>
    export type EmailLoginMutationBody = EmailLogin
    export type EmailLoginMutationError = unknown

    /**
 * @summary 验证码登录
 */
export const useEmailLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof emailLogin>>,
        TError,
        {data: EmailLogin},
        TContext
      > => {
      return useMutation(getEmailLoginMutationOptions(options), queryClient);
    }
    /**
 * @summary 用户登录
 */
export const login = (
    login: Login,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLoginResult>(
      {url: `/api/identity/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: login, signal
    },
      options);
    }




export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: Login}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = Login
    export type LoginMutationError = unknown

    /**
 * @summary 用户登录
 */
export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: Login},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    /**
 * @summary 退出登录
 */
export const logout = (
    logout: Logout,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLogoutResult>(
      {url: `/api/identity/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logout, signal
    },
      options);
    }




export const getLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: Logout}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: Logout}, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, {data: Logout}> = (props) => {
          const {data} = props ?? {};

          return  logout(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    export type LogoutMutationBody = Logout
    export type LogoutMutationError = unknown

    /**
 * @summary 退出登录
 */
export const useLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{data: Logout}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        {data: Logout},
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options), queryClient);
    }
    /**
 * @summary 刷新令牌
 */
export const refreshToken = (
    refreshToken: RefreshToken,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLoginResult>(
      {url: `/api/identity/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshToken, signal
    },
      options);
    }




export const getRefreshTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshToken}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshToken}, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, {data: RefreshToken}> = (props) => {
          const {data} = props ?? {};

          return  refreshToken(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    export type RefreshTokenMutationBody = RefreshToken
    export type RefreshTokenMutationError = unknown

    /**
 * @summary 刷新令牌
 */
export const useRefreshToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshToken}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        {data: RefreshToken},
        TContext
      > => {
      return useMutation(getRefreshTokenMutationOptions(options), queryClient);
    }
    /**
 * @summary 用户注册
 */
export const registerUser = (
    registerUser: RegisterUser,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfRegisterUserResult>(
      {url: `/api/identity/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerUser, signal
    },
      options);
    }




export const getRegisterUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUser}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUser}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: RegisterUser}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = RegisterUser
    export type RegisterUserMutationError = unknown

    /**
 * @summary 用户注册
 */
export const useRegisterUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUser}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: RegisterUser},
        TContext
      > => {
      return useMutation(getRegisterUserMutationOptions(options), queryClient);
    }
    /**
 * @summary 重置密码
 */
export const resetPassword = (
    resetPassword: ResetPassword,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfResetPasswordResult>(
      {url: `/api/identity/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPassword, signal
    },
      options);
    }




export const getResetPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPassword}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPassword}, TContext> => {

const mutationKey = ['resetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, {data: ResetPassword}> = (props) => {
          const {data} = props ?? {};

          return  resetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
    export type ResetPasswordMutationBody = ResetPassword
    export type ResetPasswordMutationError = unknown

    /**
 * @summary 重置密码
 */
export const useResetPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPassword}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetPassword>>,
        TError,
        {data: ResetPassword},
        TContext
      > => {
      return useMutation(getResetPasswordMutationOptions(options), queryClient);
    }
    /**
 * @summary 发送登录码
 */
export const sendEmailLoginCode = (
    sendEmailLoginCode: SendEmailLoginCode,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendEmailLoginCodeResult>(
      {url: `/api/identity/send-login-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendEmailLoginCode, signal
    },
      options);
    }




export const getSendEmailLoginCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailLoginCode>>, TError,{data: SendEmailLoginCode}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendEmailLoginCode>>, TError,{data: SendEmailLoginCode}, TContext> => {

const mutationKey = ['sendEmailLoginCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendEmailLoginCode>>, {data: SendEmailLoginCode}> = (props) => {
          const {data} = props ?? {};

          return  sendEmailLoginCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendEmailLoginCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendEmailLoginCode>>>
    export type SendEmailLoginCodeMutationBody = SendEmailLoginCode
    export type SendEmailLoginCodeMutationError = unknown

    /**
 * @summary 发送登录码
 */
export const useSendEmailLoginCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailLoginCode>>, TError,{data: SendEmailLoginCode}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendEmailLoginCode>>,
        TError,
        {data: SendEmailLoginCode},
        TContext
      > => {
      return useMutation(getSendEmailLoginCodeMutationOptions(options), queryClient);
    }
    /**
 * @summary 发送注册码
 */
export const sendEmailRegisterCode = (
    sendEmailRegisterCode: SendEmailRegisterCode,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendEmailRegisterCodeResult>(
      {url: `/api/identity/send-register-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendEmailRegisterCode, signal
    },
      options);
    }




export const getSendEmailRegisterCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailRegisterCode>>, TError,{data: SendEmailRegisterCode}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendEmailRegisterCode>>, TError,{data: SendEmailRegisterCode}, TContext> => {

const mutationKey = ['sendEmailRegisterCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendEmailRegisterCode>>, {data: SendEmailRegisterCode}> = (props) => {
          const {data} = props ?? {};

          return  sendEmailRegisterCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendEmailRegisterCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendEmailRegisterCode>>>
    export type SendEmailRegisterCodeMutationBody = SendEmailRegisterCode
    export type SendEmailRegisterCodeMutationError = unknown

    /**
 * @summary 发送注册码
 */
export const useSendEmailRegisterCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailRegisterCode>>, TError,{data: SendEmailRegisterCode}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendEmailRegisterCode>>,
        TError,
        {data: SendEmailRegisterCode},
        TContext
      > => {
      return useMutation(getSendEmailRegisterCodeMutationOptions(options), queryClient);
    }
    /**
 * @summary 发送重置码
 */
export const sendForgotPasswordCode = (
    sendForgotPasswordCode: SendForgotPasswordCode,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendForgotPasswordCodeResult>(
      {url: `/api/identity/send-forgot-password-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendForgotPasswordCode, signal
    },
      options);
    }




export const getSendForgotPasswordCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendForgotPasswordCode>>, TError,{data: SendForgotPasswordCode}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendForgotPasswordCode>>, TError,{data: SendForgotPasswordCode}, TContext> => {

const mutationKey = ['sendForgotPasswordCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendForgotPasswordCode>>, {data: SendForgotPasswordCode}> = (props) => {
          const {data} = props ?? {};

          return  sendForgotPasswordCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendForgotPasswordCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendForgotPasswordCode>>>
    export type SendForgotPasswordCodeMutationBody = SendForgotPasswordCode
    export type SendForgotPasswordCodeMutationError = unknown

    /**
 * @summary 发送重置码
 */
export const useSendForgotPasswordCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendForgotPasswordCode>>, TError,{data: SendForgotPasswordCode}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendForgotPasswordCode>>,
        TError,
        {data: SendForgotPasswordCode},
        TContext
      > => {
      return useMutation(getSendForgotPasswordCodeMutationOptions(options), queryClient);
    }
    /**
 * @summary 解析租户
 */
export const resolveTenant = (
    params: ResolveTenantParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/identity/resolve-tenant`, method: 'GET',
        params, signal
    },
      options);
    }




export const getResolveTenantQueryKey = (params?: ResolveTenantParams,) => {
    return [
    `/api/identity/resolve-tenant`, ...(params ? [params] : [])
    ] as const;
    }


export const getResolveTenantQueryOptions = <TData = Awaited<ReturnType<typeof resolveTenant>>, TError = unknown>(params: ResolveTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveTenant>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getResolveTenantQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof resolveTenant>>> = ({ signal }) => resolveTenant(params, requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof resolveTenant>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ResolveTenantQueryResult = NonNullable<Awaited<ReturnType<typeof resolveTenant>>>
export type ResolveTenantQueryError = unknown


export function useResolveTenant<TData = Awaited<ReturnType<typeof resolveTenant>>, TError = unknown>(
 params: ResolveTenantParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveTenant>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveTenant>>,
          TError,
          Awaited<ReturnType<typeof resolveTenant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveTenant<TData = Awaited<ReturnType<typeof resolveTenant>>, TError = unknown>(
 params: ResolveTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveTenant>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof resolveTenant>>,
          TError,
          Awaited<ReturnType<typeof resolveTenant>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useResolveTenant<TData = Awaited<ReturnType<typeof resolveTenant>>, TError = unknown>(
 params: ResolveTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveTenant>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 解析租户
 */

export function useResolveTenant<TData = Awaited<ReturnType<typeof resolveTenant>>, TError = unknown>(
 params: ResolveTenantParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof resolveTenant>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getResolveTenantQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






