/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfLoginResult,
  ApiResponseOfRegisterUserResult,
  ApiResponseOfResetPasswordResult,
  ApiResponseOfSendEmailLoginCodeResult,
  ApiResponseOfSendEmailRegisterCodeResult,
  ApiResponseOfSendForgotPasswordCodeResult,
  EmailLogin,
  Login,
  RefreshToken,
  RegisterUser,
  ResetPassword,
  SendEmailLoginCode,
  SendEmailRegisterCode,
  SendForgotPasswordCode
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * 通过邮箱和收到的验证码直接登录获取 Token
 * @summary 邮箱验证码登录
 */
export const emailLogin = (
    emailLogin: EmailLogin,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLoginResult>(
      {url: `/api/identity/email-login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: emailLogin, signal
    },
      options);
    }




export const getEmailLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext> => {

const mutationKey = ['emailLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof emailLogin>>, {data: EmailLogin}> = (props) => {
          const {data} = props ?? {};

          return  emailLogin(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EmailLoginMutationResult = NonNullable<Awaited<ReturnType<typeof emailLogin>>>
    export type EmailLoginMutationBody = EmailLogin
    export type EmailLoginMutationError = unknown

    /**
 * @summary 邮箱验证码登录
 */
export const useEmailLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof emailLogin>>, TError,{data: EmailLogin}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof emailLogin>>,
        TError,
        {data: EmailLogin},
        TContext
      > => {
      return useMutation(getEmailLoginMutationOptions(options), queryClient);
    }
    /**
 * 通过用户名和密码获取身份认证 Token
 * @summary 用户登录
 */
export const login = (
    login: Login,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLoginResult>(
      {url: `/api/identity/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: login, signal
    },
      options);
    }




export const getLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: Login}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = Login
    export type LoginMutationError = unknown

    /**
 * @summary 用户登录
 */
export const useLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: Login}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: Login},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options), queryClient);
    }
    /**
 * 使用 RefreshToken 获取新的 AccessToken
 * @summary 刷新令牌
 */
export const refreshToken = (
    refreshToken: RefreshToken,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfLoginResult>(
      {url: `/api/identity/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshToken, signal
    },
      options);
    }




export const getRefreshTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshToken}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshToken}, TContext> => {

const mutationKey = ['refreshToken'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refreshToken>>, {data: RefreshToken}> = (props) => {
          const {data} = props ?? {};

          return  refreshToken(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>
    export type RefreshTokenMutationBody = RefreshToken
    export type RefreshTokenMutationError = unknown

    /**
 * @summary 刷新令牌
 */
export const useRefreshToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refreshToken>>, TError,{data: RefreshToken}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refreshToken>>,
        TError,
        {data: RefreshToken},
        TContext
      > => {
      return useMutation(getRefreshTokenMutationOptions(options), queryClient);
    }
    /**
 * 注册一个新的用户账户
 * @summary 用户注册
 */
export const registerUser = (
    registerUser: RegisterUser,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfRegisterUserResult>(
      {url: `/api/identity/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: registerUser, signal
    },
      options);
    }




export const getRegisterUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUser}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUser}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: RegisterUser}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = RegisterUser
    export type RegisterUserMutationError = unknown

    /**
 * @summary 用户注册
 */
export const useRegisterUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RegisterUser}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: RegisterUser},
        TContext
      > => {
      return useMutation(getRegisterUserMutationOptions(options), queryClient);
    }
    /**
 * 通过邮箱验证码重置用户密码
 * @summary 重置密码
 */
export const resetPassword = (
    resetPassword: ResetPassword,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfResetPasswordResult>(
      {url: `/api/identity/reset-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: resetPassword, signal
    },
      options);
    }




export const getResetPasswordMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPassword}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPassword}, TContext> => {

const mutationKey = ['resetPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resetPassword>>, {data: ResetPassword}> = (props) => {
          const {data} = props ?? {};

          return  resetPassword(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResetPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof resetPassword>>>
    export type ResetPasswordMutationBody = ResetPassword
    export type ResetPasswordMutationError = unknown

    /**
 * @summary 重置密码
 */
export const useResetPassword = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resetPassword>>, TError,{data: ResetPassword}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resetPassword>>,
        TError,
        {data: ResetPassword},
        TContext
      > => {
      return useMutation(getResetPasswordMutationOptions(options), queryClient);
    }
    /**
 * 通过邮箱发送用于免密登录的 6 位数验证码
 * @summary 发送登录验证码
 */
export const sendEmailLoginCode = (
    sendEmailLoginCode: SendEmailLoginCode,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendEmailLoginCodeResult>(
      {url: `/api/identity/send-login-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendEmailLoginCode, signal
    },
      options);
    }




export const getSendEmailLoginCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailLoginCode>>, TError,{data: SendEmailLoginCode}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendEmailLoginCode>>, TError,{data: SendEmailLoginCode}, TContext> => {

const mutationKey = ['sendEmailLoginCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendEmailLoginCode>>, {data: SendEmailLoginCode}> = (props) => {
          const {data} = props ?? {};

          return  sendEmailLoginCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendEmailLoginCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendEmailLoginCode>>>
    export type SendEmailLoginCodeMutationBody = SendEmailLoginCode
    export type SendEmailLoginCodeMutationError = unknown

    /**
 * @summary 发送登录验证码
 */
export const useSendEmailLoginCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailLoginCode>>, TError,{data: SendEmailLoginCode}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendEmailLoginCode>>,
        TError,
        {data: SendEmailLoginCode},
        TContext
      > => {
      return useMutation(getSendEmailLoginCodeMutationOptions(options), queryClient);
    }
    /**
 * 通过邮箱发送用于注册的 6 位数验证码
 * @summary 发送注册验证码
 */
export const sendEmailRegisterCode = (
    sendEmailRegisterCode: SendEmailRegisterCode,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendEmailRegisterCodeResult>(
      {url: `/api/identity/send-register-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendEmailRegisterCode, signal
    },
      options);
    }




export const getSendEmailRegisterCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailRegisterCode>>, TError,{data: SendEmailRegisterCode}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendEmailRegisterCode>>, TError,{data: SendEmailRegisterCode}, TContext> => {

const mutationKey = ['sendEmailRegisterCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendEmailRegisterCode>>, {data: SendEmailRegisterCode}> = (props) => {
          const {data} = props ?? {};

          return  sendEmailRegisterCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendEmailRegisterCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendEmailRegisterCode>>>
    export type SendEmailRegisterCodeMutationBody = SendEmailRegisterCode
    export type SendEmailRegisterCodeMutationError = unknown

    /**
 * @summary 发送注册验证码
 */
export const useSendEmailRegisterCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendEmailRegisterCode>>, TError,{data: SendEmailRegisterCode}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendEmailRegisterCode>>,
        TError,
        {data: SendEmailRegisterCode},
        TContext
      > => {
      return useMutation(getSendEmailRegisterCodeMutationOptions(options), queryClient);
    }
    /**
 * 通过邮箱发送用于重置密码的 6 位数验证码
 * @summary 发送忘记密码验证码
 */
export const sendForgotPasswordCode = (
    sendForgotPasswordCode: SendForgotPasswordCode,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendForgotPasswordCodeResult>(
      {url: `/api/identity/send-forgot-password-code`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: sendForgotPasswordCode, signal
    },
      options);
    }




export const getSendForgotPasswordCodeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendForgotPasswordCode>>, TError,{data: SendForgotPasswordCode}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendForgotPasswordCode>>, TError,{data: SendForgotPasswordCode}, TContext> => {

const mutationKey = ['sendForgotPasswordCode'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendForgotPasswordCode>>, {data: SendForgotPasswordCode}> = (props) => {
          const {data} = props ?? {};

          return  sendForgotPasswordCode(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendForgotPasswordCodeMutationResult = NonNullable<Awaited<ReturnType<typeof sendForgotPasswordCode>>>
    export type SendForgotPasswordCodeMutationBody = SendForgotPasswordCode
    export type SendForgotPasswordCodeMutationError = unknown

    /**
 * @summary 发送忘记密码验证码
 */
export const useSendForgotPasswordCode = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendForgotPasswordCode>>, TError,{data: SendForgotPasswordCode}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendForgotPasswordCode>>,
        TError,
        {data: SendForgotPasswordCode},
        TContext
      > => {
      return useMutation(getSendForgotPasswordCodeMutationOptions(options), queryClient);
    }
