/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfApiResponseOfGuid,
  ApiResponseOfApiResponseOfboolean,
  ApiResponseOfListOfDictionaryItemDto,
  ApiResponseOfPagedResultOfDictionaryItemDto,
  ApiResponseOfPagedResultOfDictionaryTypeDto,
  CreateDictionaryItem,
  CreateDictionaryType,
  UpdateDictionaryItem,
  UpdateDictionaryType
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 创建字典类型
 */
export const createDictionaryType = (
    createDictionaryType: CreateDictionaryType,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfGuid>(
      {url: `/api/dictionary/types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDictionaryType, signal
    },
      options);
    }




export const getCreateDictionaryTypeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDictionaryType>>, TError,{data: CreateDictionaryType}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDictionaryType>>, TError,{data: CreateDictionaryType}, TContext> => {

const mutationKey = ['createDictionaryType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDictionaryType>>, {data: CreateDictionaryType}> = (props) => {
          const {data} = props ?? {};

          return  createDictionaryType(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDictionaryTypeMutationResult = NonNullable<Awaited<ReturnType<typeof createDictionaryType>>>
    export type CreateDictionaryTypeMutationBody = CreateDictionaryType
    export type CreateDictionaryTypeMutationError = unknown

    /**
 * @summary 创建字典类型
 */
export const useCreateDictionaryType = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDictionaryType>>, TError,{data: CreateDictionaryType}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDictionaryType>>,
        TError,
        {data: CreateDictionaryType},
        TContext
      > => {
      return useMutation(getCreateDictionaryTypeMutationOptions(options), queryClient);
    }
    /**
 * @summary 字典类型列表
 */
export const dictionaryTypes = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfDictionaryTypeDto>(
      {url: `/api/dictionary/types`, method: 'GET', signal
    },
      options);
    }




export const getDictionaryTypesQueryKey = () => {
    return [
    `/api/dictionary/types`
    ] as const;
    }


export const getDictionaryTypesQueryOptions = <TData = Awaited<ReturnType<typeof dictionaryTypes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDictionaryTypesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof dictionaryTypes>>> = ({ signal }) => dictionaryTypes(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dictionaryTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DictionaryTypesQueryResult = NonNullable<Awaited<ReturnType<typeof dictionaryTypes>>>
export type DictionaryTypesQueryError = unknown


export function useDictionaryTypes<TData = Awaited<ReturnType<typeof dictionaryTypes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dictionaryTypes>>,
          TError,
          Awaited<ReturnType<typeof dictionaryTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDictionaryTypes<TData = Awaited<ReturnType<typeof dictionaryTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dictionaryTypes>>,
          TError,
          Awaited<ReturnType<typeof dictionaryTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDictionaryTypes<TData = Awaited<ReturnType<typeof dictionaryTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 字典类型列表
 */

export function useDictionaryTypes<TData = Awaited<ReturnType<typeof dictionaryTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryTypes>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDictionaryTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 更新字典类型
 */
export const updateDictionaryType = (
    id: string,
    updateDictionaryType: UpdateDictionaryType,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfboolean>(
      {url: `/api/dictionary/types/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDictionaryType, signal
    },
      options);
    }




export const getUpdateDictionaryTypeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDictionaryType>>, TError,{id: string;data: UpdateDictionaryType}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDictionaryType>>, TError,{id: string;data: UpdateDictionaryType}, TContext> => {

const mutationKey = ['updateDictionaryType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDictionaryType>>, {id: string;data: UpdateDictionaryType}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDictionaryType(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDictionaryTypeMutationResult = NonNullable<Awaited<ReturnType<typeof updateDictionaryType>>>
    export type UpdateDictionaryTypeMutationBody = UpdateDictionaryType
    export type UpdateDictionaryTypeMutationError = unknown

    /**
 * @summary 更新字典类型
 */
export const useUpdateDictionaryType = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDictionaryType>>, TError,{id: string;data: UpdateDictionaryType}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDictionaryType>>,
        TError,
        {id: string;data: UpdateDictionaryType},
        TContext
      > => {
      return useMutation(getUpdateDictionaryTypeMutationOptions(options), queryClient);
    }
    /**
 * @summary 删除字典类型
 */
export const deleteDictionaryType = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfboolean>(
      {url: `/api/dictionary/types/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteDictionaryTypeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDictionaryType>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDictionaryType>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDictionaryType'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDictionaryType>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDictionaryType(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDictionaryTypeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDictionaryType>>>

    export type DeleteDictionaryTypeMutationError = unknown

    /**
 * @summary 删除字典类型
 */
export const useDeleteDictionaryType = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDictionaryType>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDictionaryType>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDictionaryTypeMutationOptions(options), queryClient);
    }
    /**
 * @summary 创建字典数据项
 */
export const createDictionaryItem = (
    createDictionaryItem: CreateDictionaryItem,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfGuid>(
      {url: `/api/dictionary/items`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createDictionaryItem, signal
    },
      options);
    }




export const getCreateDictionaryItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDictionaryItem>>, TError,{data: CreateDictionaryItem}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createDictionaryItem>>, TError,{data: CreateDictionaryItem}, TContext> => {

const mutationKey = ['createDictionaryItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDictionaryItem>>, {data: CreateDictionaryItem}> = (props) => {
          const {data} = props ?? {};

          return  createDictionaryItem(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateDictionaryItemMutationResult = NonNullable<Awaited<ReturnType<typeof createDictionaryItem>>>
    export type CreateDictionaryItemMutationBody = CreateDictionaryItem
    export type CreateDictionaryItemMutationError = unknown

    /**
 * @summary 创建字典数据项
 */
export const useCreateDictionaryItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDictionaryItem>>, TError,{data: CreateDictionaryItem}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDictionaryItem>>,
        TError,
        {data: CreateDictionaryItem},
        TContext
      > => {
      return useMutation(getCreateDictionaryItemMutationOptions(options), queryClient);
    }
    /**
 * @summary 字典数据项列表
 */
export const dictionaryItems = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfDictionaryItemDto>(
      {url: `/api/dictionary/items`, method: 'GET', signal
    },
      options);
    }




export const getDictionaryItemsQueryKey = () => {
    return [
    `/api/dictionary/items`
    ] as const;
    }


export const getDictionaryItemsQueryOptions = <TData = Awaited<ReturnType<typeof dictionaryItems>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDictionaryItemsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof dictionaryItems>>> = ({ signal }) => dictionaryItems(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dictionaryItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DictionaryItemsQueryResult = NonNullable<Awaited<ReturnType<typeof dictionaryItems>>>
export type DictionaryItemsQueryError = unknown


export function useDictionaryItems<TData = Awaited<ReturnType<typeof dictionaryItems>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dictionaryItems>>,
          TError,
          Awaited<ReturnType<typeof dictionaryItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDictionaryItems<TData = Awaited<ReturnType<typeof dictionaryItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dictionaryItems>>,
          TError,
          Awaited<ReturnType<typeof dictionaryItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDictionaryItems<TData = Awaited<ReturnType<typeof dictionaryItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 字典数据项列表
 */

export function useDictionaryItems<TData = Awaited<ReturnType<typeof dictionaryItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDictionaryItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 更新字典数据项
 */
export const updateDictionaryItem = (
    id: string,
    updateDictionaryItem: UpdateDictionaryItem,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfboolean>(
      {url: `/api/dictionary/items/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateDictionaryItem, signal
    },
      options);
    }




export const getUpdateDictionaryItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDictionaryItem>>, TError,{id: string;data: UpdateDictionaryItem}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateDictionaryItem>>, TError,{id: string;data: UpdateDictionaryItem}, TContext> => {

const mutationKey = ['updateDictionaryItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDictionaryItem>>, {id: string;data: UpdateDictionaryItem}> = (props) => {
          const {id,data} = props ?? {};

          return  updateDictionaryItem(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateDictionaryItemMutationResult = NonNullable<Awaited<ReturnType<typeof updateDictionaryItem>>>
    export type UpdateDictionaryItemMutationBody = UpdateDictionaryItem
    export type UpdateDictionaryItemMutationError = unknown

    /**
 * @summary 更新字典数据项
 */
export const useUpdateDictionaryItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDictionaryItem>>, TError,{id: string;data: UpdateDictionaryItem}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDictionaryItem>>,
        TError,
        {id: string;data: UpdateDictionaryItem},
        TContext
      > => {
      return useMutation(getUpdateDictionaryItemMutationOptions(options), queryClient);
    }
    /**
 * @summary 删除字典数据项
 */
export const deleteDictionaryItem = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfboolean>(
      {url: `/api/dictionary/items/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteDictionaryItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDictionaryItem>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteDictionaryItem>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteDictionaryItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDictionaryItem>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteDictionaryItem(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteDictionaryItemMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDictionaryItem>>>

    export type DeleteDictionaryItemMutationError = unknown

    /**
 * @summary 删除字典数据项
 */
export const useDeleteDictionaryItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDictionaryItem>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDictionaryItem>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteDictionaryItemMutationOptions(options), queryClient);
    }
    /**
 * @summary 获取指定编码的字典选项
 */
export const dictionaryItemsByCode = (
    code: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfListOfDictionaryItemDto>(
      {url: `/api/dictionary/items/code/${code}`, method: 'GET', signal
    },
      options);
    }




export const getDictionaryItemsByCodeQueryKey = (code: string,) => {
    return [
    `/api/dictionary/items/code/${code}`
    ] as const;
    }


export const getDictionaryItemsByCodeQueryOptions = <TData = Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError = unknown>(code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDictionaryItemsByCodeQueryKey(code);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof dictionaryItemsByCode>>> = ({ signal }) => dictionaryItemsByCode(code, requestOptions, signal);





   return  { queryKey, queryFn, enabled: code !== null && code !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DictionaryItemsByCodeQueryResult = NonNullable<Awaited<ReturnType<typeof dictionaryItemsByCode>>>
export type DictionaryItemsByCodeQueryError = unknown


export function useDictionaryItemsByCode<TData = Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError = unknown>(
 code: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dictionaryItemsByCode>>,
          TError,
          Awaited<ReturnType<typeof dictionaryItemsByCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDictionaryItemsByCode<TData = Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dictionaryItemsByCode>>,
          TError,
          Awaited<ReturnType<typeof dictionaryItemsByCode>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDictionaryItemsByCode<TData = Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取指定编码的字典选项
 */

export function useDictionaryItemsByCode<TData = Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError = unknown>(
 code: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof dictionaryItemsByCode>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDictionaryItemsByCodeQueryOptions(code,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






