/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfCreateMcpKeyResult,
  ApiResponseOfDeleteMcpKeyResult,
  ApiResponseOfPagedResultOfMcpKeyDto,
  ApiResponseOfUpdateMcpKeyResult,
  CreateMcpKey,
  UpdateMcpKey
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 创建 MCP 密钥
 */
export const createMcpKey = (
    createMcpKey: CreateMcpKey,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfCreateMcpKeyResult>(
      {url: `/api/mcp/keys`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMcpKey, signal
    },
      options);
    }




export const getCreateMcpKeyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMcpKey>>, TError,{data: CreateMcpKey}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMcpKey>>, TError,{data: CreateMcpKey}, TContext> => {

const mutationKey = ['createMcpKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMcpKey>>, {data: CreateMcpKey}> = (props) => {
          const {data} = props ?? {};

          return  createMcpKey(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMcpKeyMutationResult = NonNullable<Awaited<ReturnType<typeof createMcpKey>>>
    export type CreateMcpKeyMutationBody = CreateMcpKey
    export type CreateMcpKeyMutationError = unknown

    /**
 * @summary 创建 MCP 密钥
 */
export const useCreateMcpKey = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMcpKey>>, TError,{data: CreateMcpKey}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMcpKey>>,
        TError,
        {data: CreateMcpKey},
        TContext
      > => {
      return useMutation(getCreateMcpKeyMutationOptions(options), queryClient);
    }
    /**
 * @summary MCP 密钥列表
 */
export const mcpKeys = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfMcpKeyDto>(
      {url: `/api/mcp/keys`, method: 'GET', signal
    },
      options);
    }




export const getMcpKeysQueryKey = () => {
    return [
    `/api/mcp/keys`
    ] as const;
    }


export const getMcpKeysQueryOptions = <TData = Awaited<ReturnType<typeof mcpKeys>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mcpKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMcpKeysQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof mcpKeys>>> = ({ signal }) => mcpKeys(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mcpKeys>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type McpKeysQueryResult = NonNullable<Awaited<ReturnType<typeof mcpKeys>>>
export type McpKeysQueryError = unknown


export function useMcpKeys<TData = Awaited<ReturnType<typeof mcpKeys>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof mcpKeys>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof mcpKeys>>,
          TError,
          Awaited<ReturnType<typeof mcpKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMcpKeys<TData = Awaited<ReturnType<typeof mcpKeys>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mcpKeys>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof mcpKeys>>,
          TError,
          Awaited<ReturnType<typeof mcpKeys>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMcpKeys<TData = Awaited<ReturnType<typeof mcpKeys>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mcpKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary MCP 密钥列表
 */

export function useMcpKeys<TData = Awaited<ReturnType<typeof mcpKeys>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof mcpKeys>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMcpKeysQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 删除 MCP 密钥
 */
export const deleteMcpKey = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfDeleteMcpKeyResult>(
      {url: `/api/mcp/keys/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteMcpKeyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMcpKey>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMcpKey>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMcpKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMcpKey>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMcpKey(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMcpKeyMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMcpKey>>>

    export type DeleteMcpKeyMutationError = unknown

    /**
 * @summary 删除 MCP 密钥
 */
export const useDeleteMcpKey = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMcpKey>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMcpKey>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteMcpKeyMutationOptions(options), queryClient);
    }
    /**
 * @summary 更新 MCP 密钥
 */
export const updateMcpKey = (
    id: string,
    updateMcpKey: UpdateMcpKey,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfUpdateMcpKeyResult>(
      {url: `/api/mcp/keys/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMcpKey, signal
    },
      options);
    }




export const getUpdateMcpKeyMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMcpKey>>, TError,{id: string;data: UpdateMcpKey}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMcpKey>>, TError,{id: string;data: UpdateMcpKey}, TContext> => {

const mutationKey = ['updateMcpKey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMcpKey>>, {id: string;data: UpdateMcpKey}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMcpKey(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMcpKeyMutationResult = NonNullable<Awaited<ReturnType<typeof updateMcpKey>>>
    export type UpdateMcpKeyMutationBody = UpdateMcpKey
    export type UpdateMcpKeyMutationError = unknown

    /**
 * @summary 更新 MCP 密钥
 */
export const useUpdateMcpKey = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMcpKey>>, TError,{id: string;data: UpdateMcpKey}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMcpKey>>,
        TError,
        {id: string;data: UpdateMcpKey},
        TContext
      > => {
      return useMutation(getUpdateMcpKeyMutationOptions(options), queryClient);
    }
