/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfDeleteMcpServerResult,
  ApiResponseOfDeleteMcpToolResult,
  ApiResponseOfPagedResultOfMcpServerDto,
  ApiResponseOfPagedResultOfMcpToolDto,
  ImportOpenApi,
  MessagesParams,
  ParseSwagger
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 删除 MCP 工具
 */
export const deleteMcpTool = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfDeleteMcpToolResult>(
      {url: `/api/mcp/tools/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteMcpToolMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMcpTool>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMcpTool>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMcpTool'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMcpTool>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMcpTool(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMcpToolMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMcpTool>>>

    export type DeleteMcpToolMutationError = unknown

    /**
 * @summary 删除 MCP 工具
 */
export const useDeleteMcpTool = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMcpTool>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMcpTool>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteMcpToolMutationOptions(options), queryClient);
    }
    /**
 * @summary 删除 MCP 服务
 */
export const deleteMcpServer = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfDeleteMcpServerResult>(
      {url: `/api/mcp/servers/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteMcpServerMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMcpServer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMcpServer>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMcpServer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMcpServer>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMcpServer(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMcpServerMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMcpServer>>>

    export type DeleteMcpServerMutationError = unknown

    /**
 * @summary 删除 MCP 服务
 */
export const useDeleteMcpServer = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMcpServer>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMcpServer>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteMcpServerMutationOptions(options), queryClient);
    }
    /**
 * @summary 建立连接
 */
export const sse = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/mcp/sse`, method: 'GET', signal
    },
      options);
    }




export const getSseQueryKey = () => {
    return [
    `/api/mcp/sse`
    ] as const;
    }


export const getSseQueryOptions = <TData = Awaited<ReturnType<typeof sse>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSseQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof sse>>> = ({ signal }) => sse(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sse>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SseQueryResult = NonNullable<Awaited<ReturnType<typeof sse>>>
export type SseQueryError = unknown


export function useSse<TData = Awaited<ReturnType<typeof sse>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sse>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sse>>,
          TError,
          Awaited<ReturnType<typeof sse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSse<TData = Awaited<ReturnType<typeof sse>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sse>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sse>>,
          TError,
          Awaited<ReturnType<typeof sse>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSse<TData = Awaited<ReturnType<typeof sse>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 建立连接
 */

export function useSse<TData = Awaited<ReturnType<typeof sse>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sse>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSseQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 接收消息
 */
export const messages = (
    params?: MessagesParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/mcp/messages`, method: 'POST',
        params, signal
    },
      options);
    }




export const getMessagesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof messages>>, TError,{params?: MessagesParams}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof messages>>, TError,{params?: MessagesParams}, TContext> => {

const mutationKey = ['messages'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof messages>>, {params?: MessagesParams}> = (props) => {
          const {params} = props ?? {};

          return  messages(params,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MessagesMutationResult = NonNullable<Awaited<ReturnType<typeof messages>>>

    export type MessagesMutationError = unknown

    /**
 * @summary 接收消息
 */
export const useMessages = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof messages>>, TError,{params?: MessagesParams}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof messages>>,
        TError,
        {params?: MessagesParams},
        TContext
      > => {
      return useMutation(getMessagesMutationOptions(options), queryClient);
    }
    /**
 * @summary 导入配置
 */
export const _import = (
    importOpenApi: ImportOpenApi,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/mcp/import`, method: 'POST',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: importOpenApi, signal
    },
      options);
    }




export const getImportMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _import>>, TError,{data: ImportOpenApi}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof _import>>, TError,{data: ImportOpenApi}, TContext> => {

const mutationKey = ['_import'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof _import>>, {data: ImportOpenApi}> = (props) => {
          const {data} = props ?? {};

          return  _import(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type _ImportMutationResult = NonNullable<Awaited<ReturnType<typeof _import>>>
    export type _ImportMutationBody = ImportOpenApi
    export type _ImportMutationError = unknown

    /**
 * @summary 导入配置
 */
export const useImport = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _import>>, TError,{data: ImportOpenApi}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof _import>>,
        TError,
        {data: ImportOpenApi},
        TContext
      > => {
      return useMutation(getImportMutationOptions(options), queryClient);
    }
    /**
 * @summary 解析接口
 */
export const parse = (
    parseSwagger: ParseSwagger,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<void>(
      {url: `/api/mcp/parse`, method: 'POST',
      headers: {'Content-Type': 'application/json;odata.metadata=minimal;odata.streaming=true', },
      data: parseSwagger, signal
    },
      options);
    }




export const getParseMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof parse>>, TError,{data: ParseSwagger}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof parse>>, TError,{data: ParseSwagger}, TContext> => {

const mutationKey = ['parse'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof parse>>, {data: ParseSwagger}> = (props) => {
          const {data} = props ?? {};

          return  parse(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ParseMutationResult = NonNullable<Awaited<ReturnType<typeof parse>>>
    export type ParseMutationBody = ParseSwagger
    export type ParseMutationError = unknown

    /**
 * @summary 解析接口
 */
export const useParse = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof parse>>, TError,{data: ParseSwagger}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof parse>>,
        TError,
        {data: ParseSwagger},
        TContext
      > => {
      return useMutation(getParseMutationOptions(options), queryClient);
    }
    /**
 * @summary 服务列表
 */
export const servers = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfMcpServerDto>(
      {url: `/api/mcp/servers`, method: 'GET', signal
    },
      options);
    }




export const getServersQueryKey = () => {
    return [
    `/api/mcp/servers`
    ] as const;
    }


export const getServersQueryOptions = <TData = Awaited<ReturnType<typeof servers>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServersQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof servers>>> = ({ signal }) => servers(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof servers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServersQueryResult = NonNullable<Awaited<ReturnType<typeof servers>>>
export type ServersQueryError = unknown


export function useServers<TData = Awaited<ReturnType<typeof servers>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof servers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof servers>>,
          TError,
          Awaited<ReturnType<typeof servers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServers<TData = Awaited<ReturnType<typeof servers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof servers>>,
          TError,
          Awaited<ReturnType<typeof servers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServers<TData = Awaited<ReturnType<typeof servers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 服务列表
 */

export function useServers<TData = Awaited<ReturnType<typeof servers>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof servers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 工具列表
 */
export const tools = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfMcpToolDto>(
      {url: `/api/mcp/tools`, method: 'GET', signal
    },
      options);
    }




export const getToolsQueryKey = () => {
    return [
    `/api/mcp/tools`
    ] as const;
    }


export const getToolsQueryOptions = <TData = Awaited<ReturnType<typeof tools>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tools>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getToolsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof tools>>> = ({ signal }) => tools(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof tools>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ToolsQueryResult = NonNullable<Awaited<ReturnType<typeof tools>>>
export type ToolsQueryError = unknown


export function useTools<TData = Awaited<ReturnType<typeof tools>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof tools>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tools>>,
          TError,
          Awaited<ReturnType<typeof tools>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTools<TData = Awaited<ReturnType<typeof tools>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tools>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tools>>,
          TError,
          Awaited<ReturnType<typeof tools>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTools<TData = Awaited<ReturnType<typeof tools>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tools>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 工具列表
 */

export function useTools<TData = Awaited<ReturnType<typeof tools>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof tools>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getToolsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






