/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfCreateMenuResult,
  ApiResponseOfDeleteMenuResult,
  ApiResponseOfPagedResultOfMenuDto,
  ApiResponseOfUpdateMenuResult,
  CreateMenu,
  UpdateMenu
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 创建一个新的系统菜单
 * @summary 创建菜单
 */
export const createMenu = (
    createMenu: CreateMenu,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfCreateMenuResult>(
      {url: `/api/identity/menus`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createMenu, signal
    },
      options);
    }




export const getCreateMenuMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMenu>>, TError,{data: CreateMenu}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createMenu>>, TError,{data: CreateMenu}, TContext> => {

const mutationKey = ['createMenu'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMenu>>, {data: CreateMenu}> = (props) => {
          const {data} = props ?? {};

          return  createMenu(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMenuMutationResult = NonNullable<Awaited<ReturnType<typeof createMenu>>>
    export type CreateMenuMutationBody = CreateMenu
    export type CreateMenuMutationError = unknown

    /**
 * @summary 创建菜单
 */
export const useCreateMenu = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMenu>>, TError,{data: CreateMenu}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMenu>>,
        TError,
        {data: CreateMenu},
        TContext
      > => {
      return useMutation(getCreateMenuMutationOptions(options), queryClient);
    }
    /**
 * 获取分页的菜单列表数据
 * @summary 获取菜单列表
 */
export const menus = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfMenuDto>(
      {url: `/api/identity/menus`, method: 'GET', signal
    },
      options);
    }




export const getMenusQueryKey = () => {
    return [
    `/api/identity/menus`
    ] as const;
    }


export const getMenusQueryOptions = <TData = Awaited<ReturnType<typeof menus>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof menus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMenusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof menus>>> = ({ signal }) => menus(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof menus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MenusQueryResult = NonNullable<Awaited<ReturnType<typeof menus>>>
export type MenusQueryError = unknown


export function useMenus<TData = Awaited<ReturnType<typeof menus>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof menus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof menus>>,
          TError,
          Awaited<ReturnType<typeof menus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMenus<TData = Awaited<ReturnType<typeof menus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof menus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof menus>>,
          TError,
          Awaited<ReturnType<typeof menus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMenus<TData = Awaited<ReturnType<typeof menus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof menus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取菜单列表
 */

export function useMenus<TData = Awaited<ReturnType<typeof menus>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof menus>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMenusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * 软删除指定的系统菜单
 * @summary 删除菜单
 */
export const deleteMenu = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfDeleteMenuResult>(
      {url: `/api/identity/menus/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteMenuMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMenu>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMenu>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMenu'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMenu>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMenu(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMenuMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMenu>>>

    export type DeleteMenuMutationError = unknown

    /**
 * @summary 删除菜单
 */
export const useDeleteMenu = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMenu>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMenu>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteMenuMutationOptions(options), queryClient);
    }
    /**
 * 更新系统菜单信息
 * @summary 更新菜单
 */
export const updateMenu = (
    id: string,
    updateMenu: UpdateMenu,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfUpdateMenuResult>(
      {url: `/api/identity/menus/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateMenu, signal
    },
      options);
    }




export const getUpdateMenuMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMenu>>, TError,{id: string;data: UpdateMenu}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMenu>>, TError,{id: string;data: UpdateMenu}, TContext> => {

const mutationKey = ['updateMenu'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMenu>>, {id: string;data: UpdateMenu}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMenu(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMenuMutationResult = NonNullable<Awaited<ReturnType<typeof updateMenu>>>
    export type UpdateMenuMutationBody = UpdateMenu
    export type UpdateMenuMutationError = unknown

    /**
 * @summary 更新菜单
 */
export const useUpdateMenu = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMenu>>, TError,{id: string;data: UpdateMenu}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMenu>>,
        TError,
        {id: string;data: UpdateMenu},
        TContext
      > => {
      return useMutation(getUpdateMenuMutationOptions(options), queryClient);
    }
