/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfClearReadNotificationsResult,
  ApiResponseOfDeleteNotificationResult,
  ApiResponseOfMarkAllNotificationsAsReadResult,
  ApiResponseOfMarkNotificationAsReadResult,
  ApiResponseOfPagedResultOfSystemNotificationDto,
  ApiResponseOfSendTestNotificationResult
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 获取通知
 */
export const myNotifications = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfSystemNotificationDto>(
      {url: `/api/notifications/my`, method: 'GET', signal
    },
      options);
    }




export const getMyNotificationsQueryKey = () => {
    return [
    `/api/notifications/my`
    ] as const;
    }


export const getMyNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof myNotifications>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof myNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMyNotificationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof myNotifications>>> = ({ signal }) => myNotifications(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof myNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MyNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof myNotifications>>>
export type MyNotificationsQueryError = unknown


export function useMyNotifications<TData = Awaited<ReturnType<typeof myNotifications>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof myNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof myNotifications>>,
          TError,
          Awaited<ReturnType<typeof myNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMyNotifications<TData = Awaited<ReturnType<typeof myNotifications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof myNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof myNotifications>>,
          TError,
          Awaited<ReturnType<typeof myNotifications>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMyNotifications<TData = Awaited<ReturnType<typeof myNotifications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof myNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取通知
 */

export function useMyNotifications<TData = Awaited<ReturnType<typeof myNotifications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof myNotifications>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMyNotificationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 标记已读
 */
export const markNotificationAsRead = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfMarkNotificationAsReadResult>(
      {url: `/api/notifications/my/${id}/read`, method: 'POST', signal
    },
      options);
    }




export const getMarkNotificationAsReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationAsRead>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof markNotificationAsRead>>, TError,{id: string}, TContext> => {

const mutationKey = ['markNotificationAsRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markNotificationAsRead>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  markNotificationAsRead(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkNotificationAsReadMutationResult = NonNullable<Awaited<ReturnType<typeof markNotificationAsRead>>>

    export type MarkNotificationAsReadMutationError = unknown

    /**
 * @summary 标记已读
 */
export const useMarkNotificationAsRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markNotificationAsRead>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markNotificationAsRead>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getMarkNotificationAsReadMutationOptions(options), queryClient);
    }
    /**
 * @summary 全部已读
 */
export const markAllNotificationsAsRead = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfMarkAllNotificationsAsReadResult>(
      {url: `/api/notifications/my/read-all`, method: 'POST', signal
    },
      options);
    }




export const getMarkAllNotificationsAsReadMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, TError,void, TContext> => {

const mutationKey = ['markAllNotificationsAsRead'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, void> = () => {


          return  markAllNotificationsAsRead(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type MarkAllNotificationsAsReadMutationResult = NonNullable<Awaited<ReturnType<typeof markAllNotificationsAsRead>>>

    export type MarkAllNotificationsAsReadMutationError = unknown

    /**
 * @summary 全部已读
 */
export const useMarkAllNotificationsAsRead = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof markAllNotificationsAsRead>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof markAllNotificationsAsRead>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getMarkAllNotificationsAsReadMutationOptions(options), queryClient);
    }
    /**
 * @summary 发送测试
 */
export const sendTestNotification = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfSendTestNotificationResult>(
      {url: `/api/notifications/test-send`, method: 'POST', signal
    },
      options);
    }




export const getSendTestNotificationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError,void, TContext> => {

const mutationKey = ['sendTestNotification'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof sendTestNotification>>, void> = () => {


          return  sendTestNotification(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SendTestNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof sendTestNotification>>>

    export type SendTestNotificationMutationError = unknown

    /**
 * @summary 发送测试
 */
export const useSendTestNotification = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof sendTestNotification>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof sendTestNotification>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getSendTestNotificationMutationOptions(options), queryClient);
    }
    /**
 * @summary 删除通知
 */
export const deleteNotification = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfDeleteNotificationResult>(
      {url: `/api/notifications/my/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteNotificationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteNotification'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteNotification>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteNotification(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteNotificationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteNotification>>>

    export type DeleteNotificationMutationError = unknown

    /**
 * @summary 删除通知
 */
export const useDeleteNotification = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteNotification>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteNotification>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteNotificationMutationOptions(options), queryClient);
    }
    /**
 * @summary 清空已读
 */
export const clearReadNotifications = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfClearReadNotificationsResult>(
      {url: `/api/notifications/my/clear-read`, method: 'DELETE', signal
    },
      options);
    }




export const getClearReadNotificationsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearReadNotifications>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof clearReadNotifications>>, TError,void, TContext> => {

const mutationKey = ['clearReadNotifications'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clearReadNotifications>>, void> = () => {


          return  clearReadNotifications(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ClearReadNotificationsMutationResult = NonNullable<Awaited<ReturnType<typeof clearReadNotifications>>>

    export type ClearReadNotificationsMutationError = unknown

    /**
 * @summary 清空已读
 */
export const useClearReadNotifications = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clearReadNotifications>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof clearReadNotifications>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getClearReadNotificationsMutationOptions(options), queryClient);
    }
