/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfApiResponseOfOrganizationDto,
  ApiResponseOfApiResponseOfboolean,
  ApiResponseOfListOfEntityMetadataDto,
  ApiResponseOfListOfOrganizationMemberDto,
  ApiResponseOfListOfOrganizationTreeDto,
  ApiResponseOfOrganizationDto2,
  ApiResponseOfOrganizationPermissionsDto,
  ApiResponseOfPagedResultOfOrganizationDto,
  CreateOrganization,
  SaveOrganizationPermissions,
  UpdateOrganization,
  UpdateOrganizationMembers
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 创建组织
 */
export const createOrganization = (
    createOrganization: CreateOrganization,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfOrganizationDto>(
      {url: `/api/organizations`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOrganization, signal
    },
      options);
    }




export const getCreateOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: CreateOrganization}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: CreateOrganization}, TContext> => {

const mutationKey = ['createOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createOrganization>>, {data: CreateOrganization}> = (props) => {
          const {data} = props ?? {};

          return  createOrganization(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof createOrganization>>>
    export type CreateOrganizationMutationBody = CreateOrganization
    export type CreateOrganizationMutationError = unknown

    /**
 * @summary 创建组织
 */
export const useCreateOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createOrganization>>, TError,{data: CreateOrganization}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createOrganization>>,
        TError,
        {data: CreateOrganization},
        TContext
      > => {
      return useMutation(getCreateOrganizationMutationOptions(options), queryClient);
    }
    /**
 * @summary 组织列表
 */
export const organizations = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfOrganizationDto>(
      {url: `/api/organizations`, method: 'GET', signal
    },
      options);
    }




export const getOrganizationsQueryKey = () => {
    return [
    `/api/organizations`
    ] as const;
    }


export const getOrganizationsQueryOptions = <TData = Awaited<ReturnType<typeof organizations>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizations>>> = ({ signal }) => organizations(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsQueryResult = NonNullable<Awaited<ReturnType<typeof organizations>>>
export type OrganizationsQueryError = unknown


export function useOrganizations<TData = Awaited<ReturnType<typeof organizations>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizations>>,
          TError,
          Awaited<ReturnType<typeof organizations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizations<TData = Awaited<ReturnType<typeof organizations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizations>>,
          TError,
          Awaited<ReturnType<typeof organizations>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizations<TData = Awaited<ReturnType<typeof organizations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 组织列表
 */

export function useOrganizations<TData = Awaited<ReturnType<typeof organizations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizations>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 更新组织
 */
export const updateOrganization = (
    id: string,
    updateOrganization: UpdateOrganization,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfOrganizationDto>(
      {url: `/api/organizations/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateOrganization, signal
    },
      options);
    }




export const getUpdateOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{id: string;data: UpdateOrganization}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{id: string;data: UpdateOrganization}, TContext> => {

const mutationKey = ['updateOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrganization>>, {id: string;data: UpdateOrganization}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOrganization(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrganization>>>
    export type UpdateOrganizationMutationBody = UpdateOrganization
    export type UpdateOrganizationMutationError = unknown

    /**
 * @summary 更新组织
 */
export const useUpdateOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganization>>, TError,{id: string;data: UpdateOrganization}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrganization>>,
        TError,
        {id: string;data: UpdateOrganization},
        TContext
      > => {
      return useMutation(getUpdateOrganizationMutationOptions(options), queryClient);
    }
    /**
 * @summary 删除组织
 */
export const deleteOrganization = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfboolean>(
      {url: `/api/organizations/${id}`, method: 'DELETE', signal
    },
      options);
    }




export const getDeleteOrganizationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteOrganization'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrganization>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteOrganization(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrganization>>>

    export type DeleteOrganizationMutationError = unknown

    /**
 * @summary 删除组织
 */
export const useDeleteOrganization = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteOrganization>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteOrganizationMutationOptions(options), queryClient);
    }
    /**
 * @summary 更新成员
 */
export const updateOrganizationMembers = (
    id: string,
    updateOrganizationMembers: UpdateOrganizationMembers,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfboolean>(
      {url: `/api/organizations/${id}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: updateOrganizationMembers, signal
    },
      options);
    }




export const getUpdateOrganizationMembersMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationMembers>>, TError,{id: string;data: UpdateOrganizationMembers}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationMembers>>, TError,{id: string;data: UpdateOrganizationMembers}, TContext> => {

const mutationKey = ['updateOrganizationMembers'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateOrganizationMembers>>, {id: string;data: UpdateOrganizationMembers}> = (props) => {
          const {id,data} = props ?? {};

          return  updateOrganizationMembers(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateOrganizationMembersMutationResult = NonNullable<Awaited<ReturnType<typeof updateOrganizationMembers>>>
    export type UpdateOrganizationMembersMutationBody = UpdateOrganizationMembers
    export type UpdateOrganizationMembersMutationError = unknown

    /**
 * @summary 更新成员
 */
export const useUpdateOrganizationMembers = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateOrganizationMembers>>, TError,{id: string;data: UpdateOrganizationMembers}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateOrganizationMembers>>,
        TError,
        {id: string;data: UpdateOrganizationMembers},
        TContext
      > => {
      return useMutation(getUpdateOrganizationMembersMutationOptions(options), queryClient);
    }
    /**
 * @summary 保存权限
 */
export const saveOrganizationPermissions = (
    id: string,
    saveOrganizationPermissions: SaveOrganizationPermissions,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfApiResponseOfboolean>(
      {url: `/api/organizations/${id}/permissions`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: saveOrganizationPermissions, signal
    },
      options);
    }




export const getSaveOrganizationPermissionsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveOrganizationPermissions>>, TError,{id: string;data: SaveOrganizationPermissions}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof saveOrganizationPermissions>>, TError,{id: string;data: SaveOrganizationPermissions}, TContext> => {

const mutationKey = ['saveOrganizationPermissions'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof saveOrganizationPermissions>>, {id: string;data: SaveOrganizationPermissions}> = (props) => {
          const {id,data} = props ?? {};

          return  saveOrganizationPermissions(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type SaveOrganizationPermissionsMutationResult = NonNullable<Awaited<ReturnType<typeof saveOrganizationPermissions>>>
    export type SaveOrganizationPermissionsMutationBody = SaveOrganizationPermissions
    export type SaveOrganizationPermissionsMutationError = unknown

    /**
 * @summary 保存权限
 */
export const useSaveOrganizationPermissions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof saveOrganizationPermissions>>, TError,{id: string;data: SaveOrganizationPermissions}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof saveOrganizationPermissions>>,
        TError,
        {id: string;data: SaveOrganizationPermissions},
        TContext
      > => {
      return useMutation(getSaveOrganizationPermissionsMutationOptions(options), queryClient);
    }
    /**
 * @summary 组织树图
 */
export const organizationTree = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfListOfOrganizationTreeDto>(
      {url: `/api/organizations/tree`, method: 'GET', signal
    },
      options);
    }




export const getOrganizationTreeQueryKey = () => {
    return [
    `/api/organizations/tree`
    ] as const;
    }


export const getOrganizationTreeQueryOptions = <TData = Awaited<ReturnType<typeof organizationTree>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationTreeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationTree>>> = ({ signal }) => organizationTree(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationTree>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationTreeQueryResult = NonNullable<Awaited<ReturnType<typeof organizationTree>>>
export type OrganizationTreeQueryError = unknown


export function useOrganizationTree<TData = Awaited<ReturnType<typeof organizationTree>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationTree>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationTree>>,
          TError,
          Awaited<ReturnType<typeof organizationTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationTree<TData = Awaited<ReturnType<typeof organizationTree>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationTree>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationTree>>,
          TError,
          Awaited<ReturnType<typeof organizationTree>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationTree<TData = Awaited<ReturnType<typeof organizationTree>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 组织树图
 */

export function useOrganizationTree<TData = Awaited<ReturnType<typeof organizationTree>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationTree>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationTreeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 组织详情
 */
export const organizationById = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfOrganizationDto2>(
      {url: `/api/organizations/${id}`, method: 'GET', signal
    },
      options);
    }




export const getOrganizationByIdQueryKey = (id: string,) => {
    return [
    `/api/organizations/${id}`
    ] as const;
    }


export const getOrganizationByIdQueryOptions = <TData = Awaited<ReturnType<typeof organizationById>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationByIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationById>>> = ({ signal }) => organizationById(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationByIdQueryResult = NonNullable<Awaited<ReturnType<typeof organizationById>>>
export type OrganizationByIdQueryError = unknown


export function useOrganizationById<TData = Awaited<ReturnType<typeof organizationById>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationById>>,
          TError,
          Awaited<ReturnType<typeof organizationById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationById<TData = Awaited<ReturnType<typeof organizationById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationById>>,
          TError,
          Awaited<ReturnType<typeof organizationById>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationById<TData = Awaited<ReturnType<typeof organizationById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 组织详情
 */

export function useOrganizationById<TData = Awaited<ReturnType<typeof organizationById>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationById>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 成员列表
 */
export const organizationMembers = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfListOfOrganizationMemberDto>(
      {url: `/api/organizations/${id}/members`, method: 'GET', signal
    },
      options);
    }




export const getOrganizationMembersQueryKey = (id: string,) => {
    return [
    `/api/organizations/${id}/members`
    ] as const;
    }


export const getOrganizationMembersQueryOptions = <TData = Awaited<ReturnType<typeof organizationMembers>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationMembersQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationMembers>>> = ({ signal }) => organizationMembers(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationMembers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationMembersQueryResult = NonNullable<Awaited<ReturnType<typeof organizationMembers>>>
export type OrganizationMembersQueryError = unknown


export function useOrganizationMembers<TData = Awaited<ReturnType<typeof organizationMembers>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationMembers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationMembers>>,
          TError,
          Awaited<ReturnType<typeof organizationMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationMembers<TData = Awaited<ReturnType<typeof organizationMembers>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationMembers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationMembers>>,
          TError,
          Awaited<ReturnType<typeof organizationMembers>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationMembers<TData = Awaited<ReturnType<typeof organizationMembers>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 成员列表
 */

export function useOrganizationMembers<TData = Awaited<ReturnType<typeof organizationMembers>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationMembers>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationMembersQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 部门权限
 */
export const organizationPermissions = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfOrganizationPermissionsDto>(
      {url: `/api/organizations/${id}/permissions`, method: 'GET', signal
    },
      options);
    }




export const getOrganizationPermissionsQueryKey = (id: string,) => {
    return [
    `/api/organizations/${id}/permissions`
    ] as const;
    }


export const getOrganizationPermissionsQueryOptions = <TData = Awaited<ReturnType<typeof organizationPermissions>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationPermissions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationPermissionsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationPermissions>>> = ({ signal }) => organizationPermissions(id, requestOptions, signal);





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationPermissions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationPermissionsQueryResult = NonNullable<Awaited<ReturnType<typeof organizationPermissions>>>
export type OrganizationPermissionsQueryError = unknown


export function useOrganizationPermissions<TData = Awaited<ReturnType<typeof organizationPermissions>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationPermissions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationPermissions>>,
          TError,
          Awaited<ReturnType<typeof organizationPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationPermissions<TData = Awaited<ReturnType<typeof organizationPermissions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationPermissions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationPermissions>>,
          TError,
          Awaited<ReturnType<typeof organizationPermissions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationPermissions<TData = Awaited<ReturnType<typeof organizationPermissions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationPermissions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 部门权限
 */

export function useOrganizationPermissions<TData = Awaited<ReturnType<typeof organizationPermissions>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationPermissions>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationPermissionsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






/**
 * @summary 获取 ABAC 实体元数据
 */
export const abacEntityMetadata = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfListOfEntityMetadataDto>(
      {url: `/api/organizations/metadata/entities`, method: 'GET', signal
    },
      options);
    }




export const getAbacEntityMetadataQueryKey = () => {
    return [
    `/api/organizations/metadata/entities`
    ] as const;
    }


export const getAbacEntityMetadataQueryOptions = <TData = Awaited<ReturnType<typeof abacEntityMetadata>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof abacEntityMetadata>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAbacEntityMetadataQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof abacEntityMetadata>>> = ({ signal }) => abacEntityMetadata(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof abacEntityMetadata>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AbacEntityMetadataQueryResult = NonNullable<Awaited<ReturnType<typeof abacEntityMetadata>>>
export type AbacEntityMetadataQueryError = unknown


export function useAbacEntityMetadata<TData = Awaited<ReturnType<typeof abacEntityMetadata>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof abacEntityMetadata>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof abacEntityMetadata>>,
          TError,
          Awaited<ReturnType<typeof abacEntityMetadata>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAbacEntityMetadata<TData = Awaited<ReturnType<typeof abacEntityMetadata>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof abacEntityMetadata>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof abacEntityMetadata>>,
          TError,
          Awaited<ReturnType<typeof abacEntityMetadata>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAbacEntityMetadata<TData = Awaited<ReturnType<typeof abacEntityMetadata>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof abacEntityMetadata>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 获取 ABAC 实体元数据
 */

export function useAbacEntityMetadata<TData = Awaited<ReturnType<typeof abacEntityMetadata>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof abacEntityMetadata>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAbacEntityMetadataQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






