/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Nova.WebApi | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseOfHardDeleteTrashBinItemResult,
  ApiResponseOfPagedResultOfTrashBinItemDto,
  ApiResponseOfRestoreTrashBinItemResult,
  HardDeleteTrashBinItem,
  RestoreTrashBinItem
} from '../model';

import { customInstance } from '../../lib/api-client';



type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 强删数据
 */
export const hardDeleteTrashBinItem = (
    hardDeleteTrashBinItem: HardDeleteTrashBinItem,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfHardDeleteTrashBinItemResult>(
      {url: `/api/identity/trash-bin/hard-delete`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: hardDeleteTrashBinItem, signal
    },
      options);
    }




export const getHardDeleteTrashBinItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hardDeleteTrashBinItem>>, TError,{data: HardDeleteTrashBinItem}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof hardDeleteTrashBinItem>>, TError,{data: HardDeleteTrashBinItem}, TContext> => {

const mutationKey = ['hardDeleteTrashBinItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof hardDeleteTrashBinItem>>, {data: HardDeleteTrashBinItem}> = (props) => {
          const {data} = props ?? {};

          return  hardDeleteTrashBinItem(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HardDeleteTrashBinItemMutationResult = NonNullable<Awaited<ReturnType<typeof hardDeleteTrashBinItem>>>
    export type HardDeleteTrashBinItemMutationBody = HardDeleteTrashBinItem
    export type HardDeleteTrashBinItemMutationError = unknown

    /**
 * @summary 强删数据
 */
export const useHardDeleteTrashBinItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof hardDeleteTrashBinItem>>, TError,{data: HardDeleteTrashBinItem}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof hardDeleteTrashBinItem>>,
        TError,
        {data: HardDeleteTrashBinItem},
        TContext
      > => {
      return useMutation(getHardDeleteTrashBinItemMutationOptions(options), queryClient);
    }
    /**
 * @summary 恢复数据
 */
export const restoreTrashBinItem = (
    restoreTrashBinItem: RestoreTrashBinItem,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfRestoreTrashBinItemResult>(
      {url: `/api/identity/trash-bin/restore`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: restoreTrashBinItem, signal
    },
      options);
    }




export const getRestoreTrashBinItemMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreTrashBinItem>>, TError,{data: RestoreTrashBinItem}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof restoreTrashBinItem>>, TError,{data: RestoreTrashBinItem}, TContext> => {

const mutationKey = ['restoreTrashBinItem'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof restoreTrashBinItem>>, {data: RestoreTrashBinItem}> = (props) => {
          const {data} = props ?? {};

          return  restoreTrashBinItem(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RestoreTrashBinItemMutationResult = NonNullable<Awaited<ReturnType<typeof restoreTrashBinItem>>>
    export type RestoreTrashBinItemMutationBody = RestoreTrashBinItem
    export type RestoreTrashBinItemMutationError = unknown

    /**
 * @summary 恢复数据
 */
export const useRestoreTrashBinItem = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof restoreTrashBinItem>>, TError,{data: RestoreTrashBinItem}, TContext>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof restoreTrashBinItem>>,
        TError,
        {data: RestoreTrashBinItem},
        TContext
      > => {
      return useMutation(getRestoreTrashBinItemMutationOptions(options), queryClient);
    }
    /**
 * @summary 回收列表
 */
export const getTrashBinItems = (

 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {


      return customInstance<ApiResponseOfPagedResultOfTrashBinItemDto>(
      {url: `/api/identity/trash-bin`, method: 'GET', signal
    },
      options);
    }




export const getGetTrashBinItemsQueryKey = () => {
    return [
    `/api/identity/trash-bin`
    ] as const;
    }


export const getGetTrashBinItemsQueryOptions = <TData = Awaited<ReturnType<typeof getTrashBinItems>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrashBinItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTrashBinItemsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTrashBinItems>>> = ({ signal }) => getTrashBinItems(requestOptions, signal);





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTrashBinItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTrashBinItemsQueryResult = NonNullable<Awaited<ReturnType<typeof getTrashBinItems>>>
export type GetTrashBinItemsQueryError = unknown


export function useGetTrashBinItems<TData = Awaited<ReturnType<typeof getTrashBinItems>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrashBinItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrashBinItems>>,
          TError,
          Awaited<ReturnType<typeof getTrashBinItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrashBinItems<TData = Awaited<ReturnType<typeof getTrashBinItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrashBinItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTrashBinItems>>,
          TError,
          Awaited<ReturnType<typeof getTrashBinItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTrashBinItems<TData = Awaited<ReturnType<typeof getTrashBinItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrashBinItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 回收列表
 */

export function useGetTrashBinItems<TData = Awaited<ReturnType<typeof getTrashBinItems>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTrashBinItems>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTrashBinItemsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






